apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-operator-secret
    namespace: cloudflare-operator-system
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:n0kIf92eluHHnJ6ol5Gc+jSSAwv+D1GDA5vtTqhoDQCH2tzLHOQ1Mw==,iv:iKxXD5jV39VYFqKJ3FPZrzcftiYubHfISv2r9THss8Q=,tag:YmdClt/mtZtsEtK44FhhSg==,type:str]
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:FP/q3lS9jJYa3UrK6wG+/+/uNGdxrtmI7C7gFFr9F6ftKjOcPA==,iv:lZIXwLvFr+Piq+QLTXj2qfJgWgBB2+BTOtsU+nFSFbk=,tag:fsF4gflshsbQak5pEKV5dA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VEVOOTBFQS9SeWEvbVlS
            TnBscTdiTkRRS1VkK1ZyM0l4STlKV0lodUZNCm5rV1BUeUZsRERsUk9Ib21PZFQ3
            blBIU2dZTnExV21WRWtuclo5MzQvVjQKLS0tIHlyRmNzUEYySldZaHNXOGI3WWZW
            VDBXUlpObEJmZnRoNEF6c2FKa3JZMGMKlYhfQy4+SRNWQvafSZhLATnJnuOGDNbP
            pzknQfiDyAYpa7TNeP9xyC3QKzfdA21igNGUP2orVdrKzdERvcqt2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-13T15:08:13Z"
    mac: ENC[AES256_GCM,data:7Yr1KDvsuoNJVA/SrKXMQVwbYdtZiX2sT+E2Il9tOmH2VYDamhFv/G6e3ffWl45ShL28/zgvNySpZ8U71CXl/xKli5EM7bQ/H+7MmDwCq80n/9ozi6yLA4MNFEUwgJ/Q5NVSsifb+R6ZkQT4377++RdZg+ERQMj/uAZI9k9G7Kc=,iv:pZYAZCMrzHdnfRT7LDtePXCSjpgFOlCUaMAXwqlvcPc=,tag:2tP/56WT6gWOSXH0eczkiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
