apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:5Z8mTxnIB6ai7nYVKXwO/sII68Ya1w==,iv:tyojlle4d9gufLtOLwex27lW3SoK3GhhE8viM9Lq02M=,tag:i9YJHPCh2w509qKBqcdoqw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:Ss0ruiXsZBKp7nWMPkFnLEPuK+/xPlr3U0zJPV9yBK8FaBPxTg==,iv:tahB/nkU5Et9CNdnp8bE4UpoVctiuFemMZFLTng8NbQ=,tag:Ig54Op/1fyEuvEsjh+XTMA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:AigUaytTRO+EAzqNzsNWQkv9EvceEw==,iv:nS3VKFUYn6f+VS07ygpJvf4KHRmc30S3G8LUE0ho+1Q=,tag:wn/WLGXa/+uWp7GUAGyp5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdHhFTDNaVWFBUEdWbDBa
            VFdOeDNmNjhZM01OMzltbktHQlEwazQ2Z1dRCmpDSlVlc3ZmN2t6NzhER29iTXRG
            NzNGL1ovWk1kUFhsMUZINGpQZ01DY2MKLS0tIFVPMEcvb0hXQmJwVGQ5VkxObEtS
            OFBUWUFZeWg5MDkxeTZ6dXJjdzJzZWsKCcYqaWtPEi958l0xWHubRcqJvLzefrb+
            CnjG/hBv4nxHdd+dzN6Q1CMTXwPA5BNU3fFLiVFmz/kOeKyZhRyMQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T17:26:47Z"
    mac: ENC[AES256_GCM,data:xerq+8cSVETQoW5M9iTme2RX9WCpYqO+bRzskxCY1Q9iyTdf/jRyN7yVFbkMU7e1tPg3pMsqe4QrHYoAe8U+WZ/8HLLVH18xxbt5EgReK5ra1PmTnRUmypZEVURP9iqwIa9FyD/UJxiFMFdN9XdMxgUYq7Om687ccJ988dq27F0=,iv:GmBcJUgcEnNLPMxw+zjswyEkNhPCZa/cWPr4tw7Ewm4=,tag:BN7xx9QfbxtDv/BOR8+1Jw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
