apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: download-claim
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 300Gi
status: {}
