apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jackett
spec:
  interval: 5m
  dependsOn:
  - name: qbittorrent
    namespace: default
  chart:
    spec:
      chart: app-template
      version: "1.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/jackett
      tag: 0.21.1264

    controller:
      replicas: 1 # active nas

    env:
      TZ: "Europe/Madrid"
      PUID: "568"
      PGID: "568"

    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            port: 9117
            targetPort: 9117
    ingress:
      dashboard:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: "${METALLB_INGRESS_ADDR}"
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          hajimari.io/appName: "traefik"
          hajimari.io/enable: "true"
        hosts:
        - host: &host "jackett.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - *host
          secretName: *host
    persistence:
      config:
        enabled: true
        existingClaim: data-pvc
        advancedMounts:
          main:
            main:
            - path: /config
              subPath: jackett
              readOnly: false
      media:
        enabled: true
        existingClaim: media-pvc
        readOnly: false
        globalMounts:
        - path: /mnt/media
