apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jackett
spec:
  interval: 5m
  dependsOn:
  - name: qbittorrent
    namespace: default
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: jackett
      version: 11.7.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      dashboard:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: "${METALLB_INGRESS_ADDR}"
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          hajimari.io/appName: "traefik"
          hajimari.io/enable: "true"
        hosts:
        - host: &host "jackett.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - *host
          secretName: *host
    persistence:
      config:
        enabled: true
        existingClaim: data-pvc
        advancedMounts:
          main:
            main:
            - path: /config
              subPath: jackett
              readOnly: false
      media:
        enabled: true
        existingClaim: media-pvc
        readOnly: false
        globalMounts:
        - path: /mnt/media
    env:
      TZ: "Europe/Madrid"
      XDG_CONFIG_HOME: /config
      XDG_DATA_HOME: /mnt/media/jackett/data
