# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./secret.sops.yaml
- ./helmrelease.yaml

configMapGenerator:
- name: cross-seed-config
  files:
  - ./configs/config.js
generatorOptions:
  disableNameSuffixHash: true
labels:
- pairs:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: qbittorrent
