apiVersion: v1
kind: Secret
metadata:
    name: cross-seed
    namespace: default
type: Opaque
stringData:
    PROWLARR_API_KEY: ENC[AES256_GCM,data:5l7cMO6TN0ZCMEwZKsEQBqXdPOYajHeLGd0S1QXu+d0=,iv:aq/+4sNFU1HdRHyUVLJnI+/8p/iIOzgTkyiUt53r8kw=,tag:BsJamJzh66p3CoPA4MvQdQ==,type:str]
    JACKETT_API_KEY: ENC[AES256_GCM,data:gxLxstpL7KftclpKIBxIC2PP36c4TPXbtSdGJSEr854=,iv:6P4mAFXjQONPCB94xAiSVap5nvlWviVDlGv4Q2OYoN0=,tag:nsQG7DfIYhineAu8OSEe8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmM044ZGxaZERDL2M0SlVP
            bi9IQkRBYXJHN0MvMWkyWVFySW9xL2dNeFdrCmFJOWJhNk5PYVd1a0p4TDlrbkV2
            czVIZ1RMOXdERThkc0ZZRWFadmdzU28KLS0tIGh5aVFjRmtkay96UFFsem5QMW1G
            alE4bVErLzhxYlM1OG11dGFxdlJWcmsKwM4uke/B1h71rCjZ+hlxi+MuFhoVdOA/
            jFXZaGfliulVka2eV0OGZkf/+SPQUXoN7mmgLrjI+RuPmrZ9Ch7FXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-05T16:48:09Z"
    mac: ENC[AES256_GCM,data:BYr9cm0z62vA+kGtF96bFONasdkpSj9Oq+gY8hvTxfEapvbZ+D90aVDaTRvgN1zDJHLh8Ysd9Q/FDXpfKZAcC/HA6i0Win4YGbhTZkW6ztzGp1P5q43zxmVuf2oT3WDZGG9VM6nLm4Dk3uNgwO7fXMvbRP8SPcU6brGHaptgX/4=,iv:P5zVkX3Kgj3SGJNXq/8RwLQ+Ks23jB9EYV44alteZOo=,tag:b5BcSHgi/AEnjGD2Ardjqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
