kind: ENC[AES256_GCM,data:P0VU6x8R,iv:m3FNW+Nvu2HjrckkYGrraW1pcUKkZTS4vmRPFUklCZo=,tag:z2raZHqni/iGanyIzhpKJw==,type:str]
ansible_user: ENC[AES256_GCM,data:Oe7qO5xQ,iv:WuIn3URuptXnmXpFOjNOFAi3wN+SDxjbyYMXopWeWFw=,tag:YC+45mbzMwOg9VdElyn3rw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ityR5sYl/LE=,iv:tqU3hFj7eDfsyKwnwhDpCLjbAfbB/IzImBkRlasHBMw=,tag:gc2A9tsZWnkRaYFXOuVvKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cHNJclp2cTliT0g5VXZm
            b2dEMXRyeDVMOEpqc213NXRhb2o4NHN0MGdnCm9DQnE1eERGY2VNWWxTV2lmYjJp
            UDZ5RzNqa3huRzN6b3dJYTRqZmVHcFUKLS0tIG9RMHkrelZRNng1eXVVbzhhRW5G
            WEYwdG01NHZmZXd2eXNleG5YNmg3NFkKi+MW3rM4stu4OFNwaS4yFW9o1TOIUZV3
            0B2bhFNXPNGapz4oGMeTeWOxF6KHLE4Cf+4s4FsEXBgEfBNfy/AfXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-26T13:33:38Z"
    mac: ENC[AES256_GCM,data:1OdEu5hQHXqb/ho9M1tw4f8jzB43/AlVwpSjYcGUWATsLLwTdaQJPCsSzhjIccfWI/HRIZtQaUIBQYWMhzckzyuG5VjUjZWYFpbniuakQM53uWILJndSt8SDNGpn2JRgirsOG1weWmJesXmqJBcionzjT8IShbTV0YoVgoUgawA=,iv:3DimRa6mn7/3A8Kuk99UUAjg2bzg6zdR4ydF1TVrs2w=,tag:bQ/OupWerzNCOIfR1w3e7Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
