kind: ENC[AES256_GCM,data:/eKT3INd,iv:UmdfjZoH6xIQbweUsAGKsWC5Qm73CZgXITVNgAPibdQ=,tag:eDX8Nuo8UMoFXmqcDR4JEQ==,type:str]
ansible_user: ENC[AES256_GCM,data:OEo/uQ01,iv:OzI0f/y0soIHBh7ZefWoZ1hCziFWQnN5APEaIxgLfoo=,tag:js8xxFCAKQtvjvR7dH8nKA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:H8bwgHpDtis=,iv:wYGDsP2NBofWb8feeN3fn6XvNnAUIycLprVnv1PfzwI=,tag:BOLCNNYUKyqLHrYWtF5Wuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeTV5dlJPRFdGRjgyQlRi
            dDBhY2hVdlFpRko5WjNwd2N6d3R1KzIwb2tZCmtWQXdBN0MxazVrMkYrWktPTnRM
            TVh3WEs2cjA2M0gvTzVmK1NVeXppVlkKLS0tIHU2NzJtUThTVUNXbmdGVUh3c0lW
            OTRlZnFxQmRPV0RYMm1nTVJ1bzFkWlkK23/pJATdccGM9LM5Sf1w+2MFo5zXjx6r
            7+GAmviUHsNYKeuVACBO/cl9QBm80CNjeLuc44EAPAApW5Z9s39uTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T17:26:47Z"
    mac: ENC[AES256_GCM,data:71/JFFyfutP45r6DFDsdV4nCqaz4b6v/r9x2unvULT0j/uDNhlX+edWHLf0uanjArTtflmlDjQj+Zq/G3+voiQDIMU2584pZeLnqqti+ZCmVShOnbJxjUWHPiLZOpo8fXKpGNMdY3D+fiBqGmDHgfw5e0u5FsbOXj8GvHlg5jV8=,iv:380gNTdZU8AJ1qH/9tPizVRguuOjmtbCYMi0P0Po1p0=,tag:s/J4uPxCKJOQJOGTDlqDQw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
