kind: ENC[AES256_GCM,data:3nqrSCeY,iv:PPBRWei9OawbdTywi4pJ56GoCJL2x/GAHpbFX5rR4eo=,tag:t9uqEVb2vqpqZJcnTV92+A==,type:str]
ansible_user: ENC[AES256_GCM,data:6cCZ1Smr,iv:dE6z0kWdfc8UWwfPmIGsA9ihpepK3RsDjQTxIfQyI+I=,tag:JuEjYlMc/UBzFcfnqKYjvg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:JAcGt3dE+GY=,iv:qWWS0ujCq373r5j6rQJPckS2w9OPf/KUFH1Q05DAdkM=,tag:uT7F3ZSAPMI3TE8KFj8hTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dGgzaXB2N1FQTGlkNk9D
            RjZKaVhMNFd0MEliSUdHWThBOVY0QUwxbkRnCmFmdFBNUFpieXZFNlhMSFhlOTZK
            YnY1OWY3dDhnV1NralV3a0wzVWhGWk0KLS0tIEt5dGorQU5PWkEzWHpocWdEa0dC
            bFpBVmpDZkJtZGVtVi9RcjVuNEpHSWcKv2Tp9hQqyJ0wA2nK5tXf91CymaOTuMrd
            mTNRrTdJIi88UMLM4k59PSeZrbn7lh+Pc13UcOXKdXNBkGZatVrynA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-28T23:44:38Z"
    mac: ENC[AES256_GCM,data:YOryztJVxVYMcyxFiCsrEAldDHMhPCf0ObDdEyI46dVZVswofufEgMTEDhq8UEb5cMulb5XI8VTMEiTpDMhLn8Coe845z5rask6vJS1y5gShS6spxJxNnTzcQJRIzKsCzKI/ShhYFEssD9zKOz9ZPU5nfsKjLp4ro9Vcd5gkYow=,iv:iKoVN4qIMnoVsANsZOX1l+cEcG/z1Ot+u/ET52+WMaQ=,tag:p7HRbgyKk+6ETE+grWOSLQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
