kind: ENC[AES256_GCM,data:dZ9DzqrM,iv:znaVD85pnDvAJNJTVuhPuMQajnYAxJrGDbfl77STADY=,tag:KwRQIe4+ezHUiz3218Og5A==,type:str]
ansible_user: ENC[AES256_GCM,data:7zt0mvxL,iv:n7IcgHM86LsoLuEVffXhNv+JB/Sc63//nNMeZwLa+C0=,tag:4Oqwfv3toQa0vSXB2ANdEg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ndCO5lMNqhU=,iv:/95lia21eE+ARoKZPV8h/OYUjLZublCAhWH8RSA0JsY=,tag:HT1bkTRn/KgJC1WO2dUGFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5S0tsMFJMbDdmMVdma21J
            Vzg5dSt6OE8zWTY5d05tekxadXNCYW9ZL2lvClZqOGQ3T0U0QTRTaThXQ1pTU0Zo
            UHhyMWZ5THY2cy9PeEJVUW5GM1BFbkUKLS0tIHdubGpLYWpqZVhFekY5NlpHR0dy
            ODdXdW00Y25PcUJiVWNzYlE4VjJpNTgKJesjR//Drh1jw4b28Rl6iyvYiSLYY5BV
            pK+PAkTAgqaoD+TWJCgqQpkr5DrhyzG5gaJjY06SnoyVUvMPqFH93A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-27T20:21:54Z"
    mac: ENC[AES256_GCM,data:dMsY0Lm9eIrioFgIOPfmYgysnS7E/kDpPtk6CSdpYZTsos+mjbQgdQaJXPt0vuN2YmhIlUAg3gXgAd/4Tb0ZeDPpoqtTJ6UNulBUnEs5Tl3VbUCOMRfM3JFsz/uebd/dyrc0F8iAGjBI3g1ja2/y6GAkeB8zsjKFgVeV5+clmQc=,iv:4tey3OwCRgxm1338wBR2U4gVgQ11TIjNIo4fnhZrxcY=,tag:8cPjlIk1EAO/uRhHWp6yRQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
