kind: ENC[AES256_GCM,data:5f84xGiZ,iv:mI32G3Wk+R9mEb8ulQWkmlfo9z5x5w6nP5EXQJGYBuU=,tag:TMU978eH3PQfKwI7YRtLPg==,type:str]
ansible_user: ENC[AES256_GCM,data:uAk+pXWB,iv:77r5QLzVKJIrl3oMrVJahbdT0WYo4GcXC4Vol6lYeCQ=,tag:le40r8gJt1uKrWBBDwKjKQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:/lTFSCQFqSo=,iv:KpkiNd2jEDpnkc8kraVNFFvPzYqJPm32FJhnt8SulwE=,tag:f7gUUKKzScTaPT9xXga3Tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aVNlNzZDeUVObUZFWkEy
            V1Z6OGE0STdrRGFOMHNlU1owakptQTRUUlJBCjh0OGNCY3NIR0tMTkpOMmJJUjk1
            RFFndnJKampjdnBCOVlkSE12SUJJTm8KLS0tIEd5c2R0MzMzSE55L2JocGplVml0
            WlVSeTJMR0dLa2tQMmNWSWkyWjdJU00KWxMtK51HvIUW19fKL6G/Pn9UtdqAaq+8
            64UQa3dURl5shURUB8WDRN7v8RML5hWW9PBtFvfsMdCe6+s9Vzuxbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-21T19:40:24Z"
    mac: ENC[AES256_GCM,data:lmtMNXw4yNhQ3JNVxlZ3b0RvRLQ3JKO4cF4TPPr/Wywv3V7rWhSh2psAXqLIXbVGtZYTNW28FaZBI6jWf07fvXHj8PLYlr96rKHHW6NOk9k/Y51rYICGSEO7ykR82aIuLJMqX0WXlePaNoqbOcwgyXX/sVV1gFNDB92kY9kWxPI=,iv:7DEw42uZ0zQ96uLqg63RKM3Wh2n/1cSIE/cdVDAhi04=,tag:rrUKQsv9NtGKsLCc7qm1kA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
