kind: ENC[AES256_GCM,data:bE26uJEA,iv:RzLr9U7HjHCH5NPtce7KMiqC4oTnJUbsEKExXtC1bZI=,tag:mUioCgALh9p0b1D6SQD3yg==,type:str]
ansible_user: ENC[AES256_GCM,data:mvwUaSWL,iv:nmw7UsWOMOuf/AqiEbI04i48WcRhR9aWXwrHxJNmQ5c=,tag:ey1xm8DbXMxLJgba+vkTJg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:BuxrH9Td9Fs=,iv:Q8FyKf8fJVyERj5sw/F3Fh1A5X65JoCC8eLsk5puKXc=,tag:8e6Mldz9CPsTGXeu367nZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZ1ZralAzeFdLSi9MOVBh
            Z2NDZTh1WjFwaExySjVvSGc3QkFhcXU5cnljCmZ4K1k4SC9BMVZ2cjhoWFhiV0FV
            U3B3NUl4WkYzTXlNb29tUjJPUURZZVEKLS0tIENDOFFpdHAzb3VvQUpPbTR3OUVU
            S29PMEZoaVlrQkthKzNYeDJwOU51T1kK1boPq4CTuVADLglaE4tnSPbLnjXAVgw2
            wOwCnQQUvsukpRnw3Wm1L5YE+hYo3CpNx0QUd8OZwQGos54g8gpp+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-24T15:49:48Z"
    mac: ENC[AES256_GCM,data:BxMkeH/0LfXdB5GKMW+vX9YCXaqVeJXieudZfwirWL6FoAApb91mEWiBq435U8AXg0HSN34sN7GexQXVrBdsRlcW54KwhXAUjEbYywCl3U9BuzMSfKVhGbz/rIwmlulKZFMoQVHmBfV0BlHDUIKnbtI2HuOeierHZHvwVsLBByI=,iv:HbbvFVvsakaqW8BiB4dqxbIV1TWNgNjgWhLWqL6Bg1w=,tag:2gSx7wXLDlwOznCI5rCrVA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
