kind: ENC[AES256_GCM,data:X3VrFYmV,iv:y4ixO5BgNkG818BUTnbQoA5MCiz22Bn5524bCOhtyqE=,tag:dG34VpWz+FZ6qajl8raRxg==,type:str]
ansible_user: ENC[AES256_GCM,data:4r4DRdtO,iv:JKkolbPX10cZ9/SAyx/nu84Q6MpIKeoQeN7DiFJk6WA=,tag:9FKDurD/eJLEDcBuV/Jenw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:LpaAtQEtqHA=,iv:k61jKzxvPvpgvz1aoYeJ3nmPmpGdTpxt8i61lxl7tnM=,tag:/8HcpHoq6i9dFJyZQ6T+qA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVVFQRDREZzNsVG1FQlBp
            RC9nSlViWFNlVnZxUE5vcTZIUzdYYVpYMG4wCjlxbnFXa1NOZVh4aUVvVTk1aFh0
            ZjJYWUtmSytwSGprWWdpTFJRME5GOVUKLS0tIHovWFFCakZReUhQMm9uUEhUMC9Q
            YkhDN3NZZHZERFE0dXNObzRlUWMvRkUKCmjdBzQlOgYmTFIDivLjBKgHI0dpqPdL
            ZoJvIC6dFwM/Y3dGtfX8zwoKquf8Je42dYNVPQ/P50rHg6hnlucwBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-24T14:56:25Z"
    mac: ENC[AES256_GCM,data:pF1/3ZFiGnPSQbzGAlb2yTqDDNc4AbwzlAy0tPEVHy5FJrhdEEx3xsujw6+fhG09fAPmz1YuXuyzT/4Dh1wnnvTq88LjaTjVSYfcQ1OO4BmtxO4TnHdZtnst/ptUFwMUQvxVkP2G55GAS1By+QwbopHsIEsfjseAfOWBXuNX3qc=,iv:wes0aQICT6/DvpwZMtXzVwb23L97jqJ2QqhRfhTbYVo=,tag:ToWwbar2UwivrKZWZouOXA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
