kind: ENC[AES256_GCM,data:PmEuvhgn,iv:A7TCCj9WVn9xYGqRDcxvpIloQN4WsjhuRdKdjer7F+Y=,tag:h3QqstsGLwmrUVDSzvfAvQ==,type:str]
ansible_user: ENC[AES256_GCM,data:nFdlaXSj,iv:rMZK6qeHjAmLmNoOulAprWCsfStuPj7vJwkT1vWcCHA=,tag:llj4SgrmAWkIelS8YxSLFA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:JIdrDLogeII=,iv:DvpG/oFNB7QJ7VhFDLGy10aw0OZstFpzpM06grM0X5Y=,tag:DvaSjF4Jqz8x98pXjkLhWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNk1OU3FPb1I5TG5QbXdr
            Y1Z5aG5haE9NZjRpdDIxWEZ6Z1B2NjlDV1RNCkloWDl0OEpJNzRhZTAvWFpNZ2x2
            cUJqMXFLV0ZlZ1pLT0pXNE9WV2RKY00KLS0tIDE0YmZtVGlyWk1CWFBBRm5PN09F
            dHlHbm9hbHZoOTNwcUxaN01Cc25RZlkKHHB72aEowbecKtYJjNVyYWmH9NV9h8x0
            VSqXpbiZ3/AX719fmpaJmEgC7fXGu4U4wlaShIOnfhIUPf1vSWQr+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-21T15:32:50Z"
    mac: ENC[AES256_GCM,data:DfmllpMQtzT5n1Z+LZIaLvHb323Aeig28J1ea2ecg6B82I2wCSgO5BJgJVNIYcKj/USlTbLAL5c5OESieFJY716tx1wjvCnzp9NZsaZ+GZzqnxV8svYYJYtoB2rz/A0oJYpIAGJLjb+tKwq8FgxvA7cwb7NIMKWzPrRt8bjdfGo=,iv:JzTUGmP2rUUJCfwjtX+oTz1T82qT+rqB4B6ojXTeA2c=,tag:MgDTr0nLaelU7IM5U3ej5Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
