kind: ENC[AES256_GCM,data:wRWILNca,iv:FuelCzOHtyq3hgL7hJFB2w4Fow7ILQsH9Wz3mG9U+pM=,tag:wH4L9fYnLcrAwHfpBw1JAg==,type:str]
ansible_user: ENC[AES256_GCM,data:8AWoG6dO,iv:ujeaAclIbM29aELJ9THq5TauMpdLnDitfqyYfieLBSU=,tag:rruAhlgxwLSEVy4ZG9rleg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:tstD3geacJg=,iv:ZJSL/6VrgWfgDUdVngCpDHOshfpiKQ5M8IevrSjo9WE=,tag:6BVXO8mluvcvXXzDjhj9/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtT3FLbW5UVFRYSVUzR2Rk
            b3IwRUZCRnpCT0NGd2hTbzF6WXpVS0xHSDFNCkYvQW9acHdmZHpkSUZ0WGJCdURS
            L0o0cEI4M1JvRFBwdldNOXVDYWsxTk0KLS0tIEJpVkxtKy9VNlE4NmVnck80S00v
            dWJvVXNnekJzMjhFZ0FCMWRNMTVPTWMKukbq20LDIPFXu/A5bQs5BJyfDa3UnvFk
            O9x4/KTlB+7jqhBrhwwiAWQXZKcVRp92BHaO5Y0BQvNU2Cy9FROrQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-27T18:48:26Z"
    mac: ENC[AES256_GCM,data:9Bx6+xvoRN6wpnPFTF9GqQGVeo7Nqkh0r6rb6w75upZxTcpe2ffRBuC57umiTh7wGOra4h5+Dox6GTsNFWSMY6JeXk4j21Qmyv65sYlxoRcPQaqjUiDNhFbb/2mnL+hoajB3i9Q6mkxaEWp8uqxOe2TcE1Io2zNlp3dtuyQSibo=,iv:CvrtSp6q7tRkOhgOM3mAXZ9fTgpLnD7pNpswFR7Y0a0=,tag:4OEgvFG1fsiIQ1YJc9J0sQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
