kind: ENC[AES256_GCM,data:87xj8QKS,iv:bPV3fVYfB1Jf5zqGHSmfJLT7Uy76nPB+r1bYdcZ0/8c=,tag:JowO1ano/Hn8iD//EmTRCA==,type:str]
ansible_user: ENC[AES256_GCM,data:XoSaNM0Y,iv:aa303tBa35cfu3ApL6VaaQZ+d4j8Fd0dNqDQSrHC3ME=,tag:PhprXncxZCnIn455A2yNxA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:U3aaYNfuqXY=,iv:HrAcYvTfRGsFgz0FB+ia1Wug6wWFbIR1/vcKU9eec6I=,tag:z/oSSNsPRKVcS/cBJILWdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodktSYTZSVStMQ1c4ZFln
            MkFvaDhEK0QxdE14Vmd1emVRSndUQzBNelZBCmNzQmRyS2NwSHNwamRoZU1OeU4r
            STV1eHRseS9kMHVtMVRSZHErWjU3QmMKLS0tIGVXUTV0L2g3eDgvZ2R0aHpjSEhE
            cFA2Yld3b1pCWkUvK0tad3c0MEkzNlEK1rnXCRkl7XCbd1IeBhuydaEhroQN0O8o
            PkU1+DIKHeqSklS2cN5FYaF8PesKbMrX86zIsMbz4weseOBkE/VYfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-26T13:33:38Z"
    mac: ENC[AES256_GCM,data:4PTPEeqKrx+Y3Xc/zIoVnDrWqX030hHocWuavPywGnwq3H6at+6yxLpLuJysEwNBQ5v8fsL2wjjK988e/XfHDMqNIvU2t69Z7jB8qTER+d9hf3EBAKNqEKj0lncsLLo9tKexFRQxLYbgREXl9HSUjCd508neYtqjrU6UpUOVmow=,iv:G5oJK0tl8C1xQHuFSeRVt0bB4zVWC4q4U1k7fbxtcWA=,tag:RRNZ+sm78bxWJ0mB3YHPYw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
