kind: ENC[AES256_GCM,data:pnzShW89,iv:2eIM/Vx0sJ361UuLBsZiwggjPmNuTp3wbCYEh9HCZsU=,tag:k0Eo/Eyd1ux84ntCaZN2sQ==,type:str]
ansible_user: ENC[AES256_GCM,data:IIgLxPkU,iv:Nrm8C+xk48St6ieLvszQcPOlIX1RS2rt1hI/Q2tG53w=,tag:OtCpbOEUELXu3uleCABUkg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:wwLm5wIIiAA=,iv:ut4b8BVyQs76TPAMDyW1aTmd/k0OE8krhRTnHcMnkPw=,tag:r7RCPrW7wXN16AS283V+0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUjJNTnp0UG5oWlJCWU0z
            akF0bGNPYXh5NUNiTXQ4M1d4cFNMYVNEdkJvCmdnRXZMNGtVek1nazhZd0NhU2Ez
            cE5CUVNtL2JPYlZKM0l2ZmsxaFJtSDAKLS0tIHJDaFRHYUd5UENtMzhpQW5NWHc0
            ck1FaDkrcGV1Rjk1ZE1YODBvdnk1eGsKYTVdFRE7nh/hCYF2DX6hmM42jJB7oNZW
            L+AAhR03B1wsG/HIU3atY/a/u79n+baO3lVIljqiRCLV1aUm5MHxrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-27T19:45:47Z"
    mac: ENC[AES256_GCM,data:/7KAi0Twa+tuhUF0H16BaG45yELg4EcLrpBFFy5OOyrS2sLD9iQDQXCgbEpGbLGAuVCDju8pDKrx/TF9aOzo1Wvj4REe/CGIWCGp0tpYP26PcNSW9WKOaYzf3yOmNdZPKbMRrRNT8OSdCN2z0P1sYfHt+cSRlOYkL00PUt6FnT8=,iv:TAtL7aHo/CO66n0haDbYNjY9tzVIg/bA3+jQqWCbJmY=,tag:HHTzPWCKI/fdbIPcn8vb8A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
