kind: ENC[AES256_GCM,data:mLzJu8Tg,iv:Vn7/oeHRLBjFN1sNsPiuYavKc6s8q2Shqfx1yq+ec2c=,tag:o0v4UovXJJdUSbCy2gi86w==,type:str]
ansible_user: ENC[AES256_GCM,data:yTM0NVL/,iv:q9HOp35ga1AzKl9NHEjds6sTJZTvtvw6Z8WVJSGKhpw=,tag:af6j+3r70QuOvOnJZ4i1/Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:leVuFCaeMbc=,iv:iuVfHVdG4PJO55mlSf0FVAkg/Rcd+dl6umbQdx2f3gQ=,tag:+H3LkTKTEhZHX+HAusVtIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbFhrZDJ2NjNLcXQxakhF
            QW1taFdqL25FNzBNZUI1TWc5VEJQMU10WG1nCjFlTGprUlUrZGVpTTFPejNnMTlO
            djdXL2MySU5RYlc2WXJoelVvc1h0WWcKLS0tIGtTR0FOOGs4Tm96ZU1SZ0o0VlMz
            QWlZL0I5MjdKaml6b1pZeTY2RXlZalkKu3oD/hcvYHqRKFEihfRVcMc1/svVc/oI
            SaUnZpDY0lZQYLhVJ47ktr4zvm9VFeBGGZHFRc+aOqnC0djKQmKdGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-13T11:50:44Z"
    mac: ENC[AES256_GCM,data:jNYKsIJTWS04KadeCjM1JaxLUU22QwX5KVh/OEcSOMtDyws13R+WQ/TxopZP3LO8r0WpU3s+M4oL+h556o4ntje3jRj96PR4DTFNPjjKt2kWLh2RQzB7vumeNi8LEwX60qPJFnpcSfVwje2qZX7tvKwiwZLynaWXQ5YRW68eCpQ=,iv:/MMTXqK2kz3fQkAR8fMJDiu5nEwA8zgxIzDKVNazEis=,tag:89LLXk1bRXLeXcswGCTduw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
