kind: ENC[AES256_GCM,data:lI7BmUU4,iv:tzvCw8lYIXPa+HkHJzwpbWiM9S/QIgFuyyGrmXa3KCo=,tag:dOo/5bAYKYYt6vgw6BK4jA==,type:str]
ansible_user: ENC[AES256_GCM,data:yHrL4pe/,iv:6CkdelQQpOV4yUkp0Np3RBNWiqqhQXF2k7HjcWNAEMw=,tag:SGG6051LPoCF0uaLskGeJg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:wG/x4Ca5yI8=,iv:NVjOMu2IX2JQuFH3jwx61lzwBLC+q8lDlCdS4Wdtqek=,tag:dwurBPIT1lAwpZKCHuhIqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMckdSMDFaV3Vsc0tYZ0VT
            eHIwaDQvQnBnZW5uWEk5OC9tZlZ0NDh4T1ZJCmIwTlY0em5GU3R4QkN0azRuSkIv
            ZWJ1RXNLM3E1OHQ1OS83cFlPNW9hR0UKLS0tIHpmc1E0YzUwWC9tMmx4cFhWKzdD
            M0RMS1UwOHBVemdQcTJCOU1ZM1IrNjAKQoF+ZxPdCOmgKiuSaY1uhjI7W5KBlm4r
            0AKDmVoV7HHDWR1HoHvDOXy/WqARJsGDh+MD8dKMG6vO0ba1Sp03PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-27T19:20:35Z"
    mac: ENC[AES256_GCM,data:uk/6+TRK2/h1noi0pTFRi7KG5Wmb3nnNZug33qw0ywYDeGxIBfo0Tsd900ggwhkXFmm/+H1vptEeieGIlVQTNDmKZGjsXuvOIUq4UJ44SpfdFbX3QwXpkSkUNsqQ9J+8ImwkyX6ts50BFb4jtMkhdW5spXzZ0QwLWWDhW8nmE7g=,iv:vqZduP7Svvub7u9fLjoESkGAqcWMxn5GRzuqa8WjPFk=,tag:Q/WdJ57DYv5U7/CO4RDY3Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
