kind: ENC[AES256_GCM,data:suSIBX5n,iv:y5+2kcmKamuTQdR1IUygwcYUcniH9xhu48SE76v5oRg=,tag:q1S1hCdHFDgjEiSitUC+rQ==,type:str]
ansible_user: ENC[AES256_GCM,data:1iYZoccp,iv:fJDYC3/nZUsKpz1qKrPJgISbT8EkBqVrfBzjSUoX/xE=,tag:w+5/fNAshg8y7lhcEdDupQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:pq2f6f5u094=,iv:eEyxJoxYJImYOML0SqX3+40cFYtH599osBwAj9suE5w=,tag:uqxQXt37fuZI2Ypx7G/cfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bWl4NE9ML2REaW1KZ1pL
            RDZmOWYvcDMxZWpFTmYya1AwdmZweG1ldTJvCmF3S3JOK3NzdWJFU0d6c1h0cUo1
            VFdZNjJITDlLdjFQUzFDSlNOdTdGKzQKLS0tIHZET2d3TUgrUlpaSU9TRUNSU0dV
            UkxaZDlzRFVLZlVVVyswcmFhWTc5ZmMKOBwbmOsvLMqjKN66rPNIWJJO9YmKuwRj
            6hGmfAQuGGpc+34JIBxzEw8EgGca54o5A4aNf6oZykiStcH0qnng8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-26T13:33:38Z"
    mac: ENC[AES256_GCM,data:b4pFh1MGsdC1w+Eac8RXnbdUDuIQfldFt/81xx5bzbjccsc5HkG0t1WnlkGvORdUiGyE8AMYc89xik3iDToZJnB0Qdd51CDNwDPNf4PLRKO2QY0XB3ul99nXEkXxlsYkp9ZFoDII6TMJ8pKu60L9//wOEqIkDGEXZ9iugl4s20Y=,iv:ziVXV9nfM7sg3mGpxtBEbIW5del1O51cu5W7+ZzE2wo=,tag:fEDOw5HVW8X5746w/Ko/wg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
