kind: ENC[AES256_GCM,data:ELLz2Mka,iv:uh82BMwu9UK/nGNgJ7FCFopEjGGm7bAaT2zdv02x0yg=,tag:cPzpv1Utt2rLMrm1nqnYCg==,type:str]
ansible_user: ENC[AES256_GCM,data:O8vyFNu7,iv:vyjYQlL0PPQJB67Gba+oDivo+iezDfGmXynI/Uo/T1Y=,tag:fP5csfaCQZpwFvGkML8CMg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:hwNllemdiNo=,iv:xl80+qcPpuToYG0esNgheaG+hYvNBl0lmX3+a5GZnLA=,tag:7J6T4gB/Q462N5GSmXEL4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWU5yV3hMWFUrMDFmN3RY
            L2tiMG9TdE51bjEyVG50SUV0d284dTF0aWxBCmV5S3BiNFMvZVlGZGpNTUc3amNW
            OWxvblRDclgxUTVzVnVUMSt6OXdKczgKLS0tIGpTeGxwRkhOQUZPdDd4KzJaeS9P
            Y2M0VERadWl4cW92a3g4WGpnd2x4NUEKsGXitI2GrAg7I3p3XgVQXXR4zdaovUCq
            00Wrha8ZpVhEYfkXyeDTNrnE6sOpK+z+Cq/fXk1HbbSYIjRE4I/25g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-21T15:32:50Z"
    mac: ENC[AES256_GCM,data:Eo8+2Kbr6bBIrgSrwRPqdVcSO4EjITTAmVdXggmvGRT6ndwSDiSS/jeUrht/baS9dylWhmaCcPLDe+9h5R/RAy8G9SmMFjn9qscnQ7T+OXWJmNg6NSAJwngbhnT6tQv9qY+CRyRcBMq1d9kCudo1oFSo3WLANbjRVkntt3jYPc8=,iv:yzW0IYtB9Kh2y+kQzZsnbBOSZHdAmkAAN7XNn98t+BY=,tag:+BbZuF7TTSA5gVBslOCigw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
