kind: ENC[AES256_GCM,data:kuqrBQts,iv:3psetlg2R37xzAGopc3B7wS1xz0ud7YxDXEwObQBXV8=,tag:IGc7VTHHZJbf5n2DKh4XnQ==,type:str]
ansible_user: ENC[AES256_GCM,data:yI6H8Nxe,iv:FNYplD9Wy29P/cW2H0Za8a9d0u/tAdC2up0zviEltLE=,tag:hVIbuPwg54lP1/xxr/Qvbg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:cOxxwKWFJmc=,iv:hMGN3MXqzNHlO+5cH5QLsvs0jvJO13+q6s6EwGrdTeY=,tag:YW+7jvqaWHgLrNBrVInugA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWUc1aDRtaHFHOXN4Qi8v
            a1NYWmZkay9XeUJMOEJ1eERBMnVsUG1CU1VvCmJGVE9kT1hvRU1RMGJJVUNBNFJt
            ajV0WldMYU1PanppU3h2c2dwV0M3WmcKLS0tIDJCcmhKbUZ4S2xvTVNwMmliOWVW
            SmJCWWRjL3drNCs5L0JBNFU5eDU0YVEKgwgoia8p8RSyIboE2hxvQfd3Z3nneZMw
            6jIuJghEv2L8NVTuAKVVMAYvf9i+SVhJ7HaSpBtboBwYZuVsqBDrhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T17:26:47Z"
    mac: ENC[AES256_GCM,data:LJvwraIOXeYSnDTcsiFb7rw3Tp2ipEwAJNClay/EIdS854zNxF+6V41e7GrKIzQsYWSiNjzShH5kMhrIx26ufPyIcQ6kapITaFysBo6Lhwa7AFh01rQJYZDFYcCfToAh02OVl1LAtb3XBgVi3HC0uoQY5d9i6FLT4k/Krm1X3iI=,iv:iiMnhqqGn1IGsmzTYoGuVIFMr6V/A1nr7UohpXPqKrI=,tag:s4E18waJZkZnSzIFCvGnkw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
