kind: ENC[AES256_GCM,data:qXx6zXi+,iv:ab05Lhd5lJVVoL+jBmr8xMYF4OD55a+nuj7d7KoilhQ=,tag:+v+tmCvV0jmWCFggB520nA==,type:str]
ansible_user: ENC[AES256_GCM,data:MxnxVfqj,iv:f4qNalpQC8sye+YobXKjAg7DY/ZIV8iEN5i+ivuQwZI=,tag:qliZiU0HmsZVjAr2mdgC6g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:su9UoFkvVcY=,iv:ggt64JrTfKy76qN+GfoFZsYv51epLT/EF42Q+gqoiPs=,tag:Tu5hFwSekgmJiPZg+XbWng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHenZYSDBqWUJnOWlhYWY4
            Rzh3RFJ5WUJtcy9hN3l6MHNOTWxJR3VxcVE4CjgwWUltbnQ4N25hTGVBMTQ1bkZT
            eVN6YW1vMXlRS2YxQ2pWSUpSQWVuTlUKLS0tIFdOT1hjc2ZtQjYvbEJqbEN3MU1u
            ZVRqVXhneU0wOXRyMlhXamFkc2x0VjgKMMRGB4YOLrvR0QNzoNpyWSmRbthARwcH
            lNcoVXz8eGbgp7l2e7eW7i+7r+n8/VxNV+1Tfo5F2q1GvBo97FZyTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-13T15:08:13Z"
    mac: ENC[AES256_GCM,data:XGXqwaEhYqAbZUuvdgPvTVgRCCM/0/aO5zYb+AcqvwEJa9TtRLTvoCDiFU97kb29oR0k0x5O9nuTUXcnu6khe1uLJB68IKzps1Z/fVqsSjzbmTNobAXx7KW1zqaUNBpAPYb6NUwk5nIfq3Abq6zdDI88l/ADVCDB9dPqKTHixHQ=,iv:EhG2nogqRqmq7ILQeOTikhMlNRvOiTi+s3iaBQnE56s=,tag:x1cFp67fK2/WWvlB4CAEUg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
