kind: ENC[AES256_GCM,data:7hns/Jlc,iv:0HBGxRpWpanTcEA/SQ+z876tj3+iywvVCXnjrzf0bpI=,tag:gySuhJUt2/JCv4KbTXbUgQ==,type:str]
ansible_user: ENC[AES256_GCM,data:jEr2/+vw,iv:FqoRFSo4jSGTMZc/7GXRusNspcXgHVl3fcGq0BMbX4k=,tag:47b8sugbx7ukt1uyHyd8Ng==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:/4RNbUwoejk=,iv:zpcRu1bUEM1YhJ1TAio0hkws55lOu7Jzzl9p88DyjWw=,tag:YOTgF88rO6izNNQmEaSCRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3R3lkQVpVb281amlMMEs1
            MFV5RTBWTnZ6bDRNNWR3MXk0Znc4cjUwTUdRCm5CdHF4eitpeDNIOVBsOUhJTkxH
            b2FZU2N2YjZ2VWFwV01NcEdIVTI2K3cKLS0tIHoycGt2T2JaRzdHcVlicEpGSldR
            bnpvQlVIWFE3OHhSWWF3dXZSNE5ycUkKTPk8iBM+Zpfgb5BHlXGm1oZIxVIK4I0U
            ytFqYGa0EYcCxwbvEVVIoTPduunI4dIhzLmCs0QoPvmOdzx+MIFXpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-01T23:19:20Z"
    mac: ENC[AES256_GCM,data:UKoFOHXtlGHhu3cp+lzMTrgpSuACsgjPxg191nlL/jobzoxj9rEGXZU64T1hoVQ37GWKgpXrF93UsqF+TlNZR9s2fvI0Xu1MShciZ83wB3B3nCkChn3JpqXNA+MtsvWgzW513Wnc++LoRmIl6z/U0uYz/M04/UBhmL8ZnKK8lVU=,iv:7iupC+FwE+tdxTABuHWsyj4pDJ7owpRffzxsMwRBqak=,tag:/Pf0MzjTT49ENYywWs0gMA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
