kind: ENC[AES256_GCM,data:3pQbk6Lq,iv:/loj7FOplxjds6ZhdMk4Et69XfNTgWwUt7MK1VYzm2w=,tag:OCmBNqze6O/x4Mh8RS3pyw==,type:str]
ansible_user: ENC[AES256_GCM,data:41zkEhwR,iv:dy3UEibEfDWYkqBld36NbO9sC2I49YLZA1ZH4vSFchs=,tag:fCNhOhGqMPpeQzulbQCwjQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:84/tI7hEK3k=,iv:x/vnplod2IL2B21aCkKF7TWtYv6TthPLxsE9inNO2Gc=,tag:H5MtumMNWCDOy37afmFteg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOW9RRzY1NTRmSFVHY3dX
            OXN5Z1dNRStHUVdYRm5qRVZuN25pWFgra2tjCldQaWhIYUFXdlp2a3dPMUplNDZT
            ZlB0cFFuQ1FSZkFrUDR3R2ZvZmZ1NWcKLS0tIEgwLy9GaHFCcWlMRTdWN1lYYWU1
            eXNIUk5iRjRyVXFPS3NrbjhuSjlpTUEKx72Ya0+n7d2gjtuSCnTADyibKx6ckFJI
            IFR0mBOTwH0DQgNUryi0ZrE8BPCr7cIi7q2gjk7s0zWm8smM5EcfoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-03T23:27:18Z"
    mac: ENC[AES256_GCM,data:S6eXQODfzZxO1UxgNpmGTHKTl500qLIt+ZDjnrxaYzqm7kntUf8De0yJVvU/AQOKnwbD1D7ED9vG3GSK7kV9MH/mq/9Gtf4P8DtSK8o5qrmH12eEa8IMRlS80AhfqjCpAwrugX67o5wZy+GOnXONlX+tIoBzuJsQWb7F9tOD/z8=,iv:LY59pesnCOvFGbW9S7HJVAiV+LbnxZXQjAMZV/2nIpg=,tag:fJ6ABcWRRTa23/HxuDD9nQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
