kind: ENC[AES256_GCM,data:KQFtx77b,iv:P/i5/v9uR3JEUsS4fWY8YRPqbDiM44nFA4h/j0HepOo=,tag:nxfUNmH9ip/I2/hdgjURFA==,type:str]
ansible_user: ENC[AES256_GCM,data:LhZZKD1j,iv:22IAwK98GN/ont9hQUh1iNjMvvC0g9MlMglvrM+WJsc=,tag:uTXDolViw91+KFNYFYwfVQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:CmV0BpjNpTM=,iv:RbEzdh/fAQ/9aJbOdVdQ5sY+H7vOF12knWxYIHT12As=,tag:PggbIBvavlYfd/oQvA+6lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArK29jQmdvcVRRVmNLdXVa
            Qk9uVlZSRGlLb0FKM05nczFMTmlvb2gyeEVvCitvZExOa05OWEN6NUJXci9yaDN5
            UERqbU1iZWpYYzJON1BObCtEWVE2dnMKLS0tIFFyQlhtbkVha0tjQzBXdWM4aktS
            QWl5aVhkK09Gd2JjOHozdmNadndKdXcKUa4KZ2mnQQYou/trz2c+AGc0w3z3jaVR
            IJKpLLr0aj9NAcLDvH9Gb9KHHbXen0UphDZMDvzDW2ncdHALrZiblw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-21T15:43:56Z"
    mac: ENC[AES256_GCM,data:0UJQDXfKBcDlkYJcaecoqHCKsNTLTwD+rzv2x7/jvh4FKa+gxDLWpgeikcnb4swzxvqbUSL65Tg2+/gO1haPp4ZgvWxisraOiQgO1KAe7eR1gkIPrF8d/rx6n0yd0gd41fSb54uRG1+8k7mzgMRDnHgRUwgb6xSBm5qLI7LR1RU=,iv:SfgMdIWKvU/gwEPypc9WkGiCEeNlASzmDkhE++nB1EA=,tag:Fg7B1QrJO3v1MQ+opWTjyA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
