kind: ENC[AES256_GCM,data:LKLN6EEI,iv:w9QClY6WjE/c6cFhZJ2UMbC12WvMql+Pi/K2AWjyBN8=,tag:neBywyqwt8gfAQ6RlQk4tg==,type:str]
ansible_user: ENC[AES256_GCM,data:gvS1OHur,iv:1oJSnAM7XJ8w1ORXyOHHfmrbdFhMkGZ5o29kKxgBBOQ=,tag:6p/8b7R6PO/DiGl9hiv8Zw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:rsABikIYwuw=,iv:Qnc8c8hH+wMHdioH9O3qrRQaWqvT3pMTrtKyjYHzdP8=,tag:HNIRhcoW3c3Kspq//Qm28A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlOXgraW5yQkNVZjY5YzVF
            YjY4UEhNUDBKUzhqNmJwanBSUGQ3UmxpcmxFClpDTUhjaWNrd2prWTJsaHZUbXNC
            SVdYTlVyM2wrYk9DaXgrQ0pGM3QvMUEKLS0tIHU0RHFPNlhFWFNjN1BhUWZ4K3Yy
            VDNDdTkyd2FWT3VPRDRNYTdUNGZ0RzQKDT0PRs4B3TytE2u+3xXBafE28cpwIoZz
            eYlXDHyoUo0I4sNTv+mC45knbVBCOtKyNvbi/YjVrgFqANMpHFVm2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-27T18:48:26Z"
    mac: ENC[AES256_GCM,data:A48UTS/fZCP02T0OJIEpC9Yn4TvmZ5leyqyBmB/rW+HjcZdQm7Os3KErU628UtjqzMjhK/DqKBsGGdsH70CFXqqu98ASlccKCo/PYECpKN3kkip2Dd3/G7ct5U+JyRIYyQ8WlOfH/xyLB4Bv80ME2wLX3ps0v9HRSTFb0kw9jQ0=,iv:Ic9fLBcO9GI48oGvwLKyXRXp7W1mJoZSDDFb1mVoX/0=,tag:EHH3PLYEmFqpDEYre3RT5g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
