kind: ENC[AES256_GCM,data:k6lpal3j,iv:9edVp+McUYgtZi7TnsIadNQrO7/0preOzfJRih6KipA=,tag:MCM+BnCNhcfFHq0+zXwLGg==,type:str]
ansible_user: ENC[AES256_GCM,data:FtatqJ5I,iv:+NItGF70OJWcHzLErvRog4ibLjigflmFxQHMpXFoKCs=,tag:7PIhumBgBLIt6EYbbMZHvg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Z8UX5k/+Mmo=,iv:WX3nUgM61ZTitB1UH4SleI3hKUPRNlWfA4c06BTVWzU=,tag:FnDVuQm5g7aRLiM9To6bTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQkpZd2NnNTdvejlXN3pU
            Z05tRndJVnI0RHd4R0hMQjd4YkZ5OU5CeTFRCnllNksrMENXUFY3ZXl6V3o0V1hF
            cGZwcWJ2OTVNZ1p6a21vbmZDQS9udkEKLS0tIENpTWdpUnBCTDZQT1N0bjBuamcy
            UHhwRkk0aHFWTktGM3c5NldWcVBVQWcKTObTNkaKYozVRpzRwSLPWHCUaLE4nRzg
            t7RIIJRKNt4E21Cn0BY4IUAghMxI7shLe0ayh6KR8NIdyAXD23PvHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-27T20:21:54Z"
    mac: ENC[AES256_GCM,data:5a8ZV+DGhxiZWFnV8TrPvtBTC+EdMEKDeD3zoaKcYw7uhpXdsHu2X7rDRPDBoA2RXoOdYLfkhlq2FEpkJNMelIFYeaQVC3FOzcP4ILUc9LQ1FG44Oi8/3w15KjQmWGuteHOPkhdeHBgSCorpgKM7KsE2ESI0JnasjbErjepZ0CQ=,iv:/MhvJ7H2VrPDSr0E/JTcplzDOb7Mp+jNqYja5jUAICQ=,tag:aTTjJAtvKksua0mK6Hyx1A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
