---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./external-dns.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./prometheus-community.yaml
  - ./rook-ceph.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml
  - ./grafana.yaml
  - ./pyroscope.yaml
  - ./timescale.yaml
  - ./descheduler.yaml
  - ./botkube.yaml
  - ./longhorn.yaml
  - ./fairwinds.yaml
  - ./vector.yaml
  - ./external-secrets.yaml
  - ./1password.yaml
  - ./traefik.yaml
  - ./beezlabs.yaml
