apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: stash
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: stash
      version: 3.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system

  maxHistory: 3

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  uninstall:
    keepHistory: false

  values:
    image:
      # -- image repository
      repository: stashapp/stash
      # -- image tag
      tag: latest
      # -- image pull policy
      pullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 2m
          memory: 352Mi
        limits:
          memory: 2Gi
      env:
        TZ: "${TZ}"
        STASH_STASH: /media/Organized
        STASH_GENERATED: /generated/
        STASH_METADATA: /metadata/
        STASH_CACHE: /cache/
        # STASH_EXTERNAL_HOST: "{{ .Release.Name }}.${SECRET_DOMAIN}"

      probes:
        liveness:
          spec:
            timeoutSeconds: 3
        readiness:
          spec:
            timeoutSeconds: 3
        startup:
          spec:
            timeoutSeconds: 3

    service:
      main:
        ports:
          http:
            port: 9999
    ingress:
      main:
        enabled: true
        className: traefik
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: "${METALLB_INGRESS_ADDR}"
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          hajimari.io/enable: "true"
        hosts:
        - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
            service:
              name: main
              port: http
        tls:
        - hosts:
          - *host
          secretName: *host
    persistence:
      config:
        enabled: true
        existingClaim: data-pvc
        readOnly: false
        globalMounts:
        - path: /root/.stash
          subPath: stashapp
        - path: /generated
          subPath: stashapp/generated
        - path: /metadata
          subPath: stashapp/metadata
        - path: /cache
          subPath: stashapp/cache
      media:
        enabled: true
        existingClaim: usb-media-pvc
        readOnly: false
        globalMounts:
        - path: /media/Organized
