apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:BYg6CyVeBvgxxnt+bMxbmnQvmsxUUlcBnpwQs/m4Z+C1mxWg1ogdMg==,iv:z6t4wg10fOuKrK7bSwylVXkaGsasr+G8/jatIOx6e5Q=,tag:M7R8TTswgPc1DUG5Qne03Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWURZd2RBOGpteGoyZnZl
            anFrcFJwRjFxemFlOGxWeUhzdEtMTjBaMWlzCjBPdE56d3gvM2pEU0poRFAyRXM4
            MHRRUmk4UEpBalVtL3UyZ1hyNEdqbGcKLS0tIHB5QWVXS1h0ZFhiL2lWckxpbWdJ
            WkxJUERML2JUVEY1US9vRmM0dG83NncKUgmQD/5M1b0eZ3eZEwVAf9FvRoyyn904
            X8KXz1sbGKCt/qoc1JohYvFLfEz160fxaunbgdQvkTkOncFTL4Q7Dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-28T23:44:38Z"
    mac: ENC[AES256_GCM,data:K5vqzVuCJOGYC1hQhLv7fpZnUpy3kTSoG+SLoWgPZDVV2QNW4nV7J0Wm7F1oXpYukGpzj3jmPwXNtDBea2odePlPGE6tW1KPfx8CnOd4vFD6CU0bI2Q/hY99VMyYAcIHfLy9ciJso6TKMZ7t2EPoIUv8o71Bgjw0bOWrwGcGE/Q=,iv:qimq38bw309qDjQKFemLkJMoNcm/0yjl6DpEluxOjUE=,tag:hPDYIdCKRkqAG8RTxYwG/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
