apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Pl0shJ/00Su07FE2cq4Wso3kLRxs2bJCJx/7PQqIWbNYL1NO8ZWteQ==,iv:+6thtqEtjVV0XDnH8uTO3P2iZ5cyjR8/HOLDYNpeuZM=,tag:HEeKDRyO+IBwKNfgnxb4Ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPL0hEVWdzTk9rTmxiZ3dp
            UE80SlNjL2F3Ym40Q3NxdzE3cWhqd1l1Y0hvCktZRUNTeTEzUVZYSUdIM0x0Y3I4
            WUg3Mm5tb01jeXAzdTc3VmF1V05WRUEKLS0tIDNSTDNGU01qVXQ4WXkwRG9DMkY3
            NDdmZkhiSjVsL0RrUFVmU0o1RmRObjgKoN967CTFlgzLbuiqGs6q0oAirPpubvsl
            EU4O0rMo0GuJTfZhXVJU7cWezMFiRzNXeZwcERFGwCHegCvaLxaJpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-27T19:45:47Z"
    mac: ENC[AES256_GCM,data:MllsK/MiqhEFl01PEHVr5acJisHu5a5RbVAtLSoEbcioEYBSKkLV7qZADv3eZ5kh5pem8M6KuE/kryDZbqkyuOqbCgRzusAC8ONS5RnuRbhp0MFouZO+4YBZVW6MLbmcNLnXzvD41sLwITrhAdoRPfysDv7NFCthki8NCkuCfoc=,iv:bSgF3RpkEvJXh2Dnv5GSmEiJog+WU9O73WUthktQHws=,tag:MoqYQQPA9xYI5a6klGwc6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
