apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:6qPj44N6EQqPGnlYJgC5TQAk7xWADBRL/+98qoZDivhYZE0+OEjDqQ==,iv:5cr+IJ/jvX5W66TOJUV3Xh99qpHkDQ7yLYwUj8Bfkh4=,tag:iLNk1jywjVpw4AXqeAFIwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMUhyQ1YzbkFHRVd3R0xz
            a054UGNFS3cyendQQ2M2TmY1SkxoTEJZcFhJCmY3dDZ2NUN2SHliTUhxbFpNaDlC
            RHFsYSsxQ2NEQTNld1NNcGdnaTNGZDAKLS0tIENLZUJ1WUt4R3RHUHRvSkVEUFRn
            RkI4Z3ZkTlRkbEpVUDRYNmFudGgxK28K+IRDcsfW2ZiYm4orATTe32HxyMMLsogK
            1+ZyWmmAkc3nCki8QYKNJ79D+NRkcD+TmDtb+PJxaE0+/Df4eeY8bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-27T18:48:26Z"
    mac: ENC[AES256_GCM,data:vfJ85p8UWmW0fea2/jkEmVM3Qkn0TvhtnJfV9yWEALO7lLweeLQUpwgFr68qv1T/htNnWFgWKHubbG/Ho5Ya/PLkAVwYXB4vF1voSH1rQPRBiFqQMY2v4bbdxT7/1dGl90pjrxEZoAMjnMgkYbWhh3EelzDv5xBlrH0dnav7N+A=,iv:Lynynp8PsjguIoVng1yDDG1OD/+eecJK7AkixDbZsuw=,tag:WXVFvQ+tGXStAvdfQQyIvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
