apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:RrYHhsthM9VExwsohmHwCrNd1NXZM8t8cUqucB6apAJCAcNhX0GuYQ==,iv:uev5Jrk762vedDjgTbNzNR2+BV5Ex9YNy7NVnWwDm1w=,tag:tfDeQLDVt0cK1mCz9cuoyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTmlOd0xyYXQ0a1hPTjFx
            dzRsS3NjTUlHN0RCMmE0bk1tVTJNV0E4VUJVCmZXSFVmdVhWQysya00rdzlqcjlz
            WS9WNm8xWW9DU3EzUXJoa3doaDByQU0KLS0tIDh0NHoxYUJlRS9UOFRDWHhkSllQ
            Sm1Xa2lkL2s1SnUvNjFna3lQTjhSQzAKiuFdVO0PWSjichufkLmQgRxOcM0SqvO8
            5Dx9r8L7JaeQDQ8CB7Wjb3JG2ZzfRWrap8NDg8/XsPMBc9NVSqR6Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-21T15:32:50Z"
    mac: ENC[AES256_GCM,data:oUo/cRiMAYGzyjDO36vteuGC9c3nHgxH8KI6ocOYwosxr5+HA+lBfd8BZAUIJ04npcjR6QjmYRYueDsJy+Ygq9RFdDXt7QQePk/virjMA4x5fpQk7dGrRZzjqv2bzrL30Eini1ODyURuB9RBThU1//0XWhbcRAuMOtExI7V/GAA=,iv:zQSNUOm49+A1xVjOXZTklYzxBKKw0XgB/h16RiKeyTw=,tag:DkoG80n0+3RN/43zIwkMfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
