apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:0/VhNi8UUZuCzKPTjuRiTFEzJrTEih4hykYdCC6MMZVaR1d5P3mPCQ==,iv:apMI3UTZXFuJEYpRBV3im43xcSWnYJfg84DhjS9xflE=,tag:tVSkfcgDf0z9WUhQvHUeSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTkRaRFJuWkdSWFZDQlRh
            WFRsNHREeSs0RnMyWFc1eGpZRmorV1Mza1JRCm9hWk5PY3JjTEpTd0VsTy9jcHJR
            Ym4rb3c5eTRNSXIydDdOd2tFSzduUGMKLS0tIExvYjh6TFNVdTRaeDU2TmtCODNj
            UFY3ZENnNG5iM1U1UHhQU1JnR2ZkamsKDN+A+d/BsAIUQgaSPvEmHaU0k5FMxRy5
            xJt1o2oUiK3/mCakZjSpE6IMpPat/4cjZvDRLZh6QaCgebPxJ3WIZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-21T19:40:24Z"
    mac: ENC[AES256_GCM,data:lM1fNjtWpbaVElRrf0YG9ehTb4mEoQGDZgEjHYQJoHgnK6ynArrx44kDiblDDqZtxNZLCkofC5vZmEbfEK7Ip7oaAo7ScIzC7WDQQhbsVcpU2yVssw6FsFshwIMEDBL+/MS0vCPvyJbfCY1PYVJwQnIVVoKeCqeqVdn7lLhNIgM=,iv:E96+MP5S5+QIMhAs1IwMIryXbAYCvQUeOX82SXzvbc8=,tag:jirDVWfrkKxsM3l/kjXpmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
