apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-operator-secret
    namespace: cloudflare-operator-system
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:cw66rggJhseKNz0RAyBjh1ZcbAm+RWmfsTBOnticTYztf55XCl1aLQ==,iv:rDeFqRi4G+qER4IK7KNn34lLYLLR3q5gcErIdcJPmTo=,tag:izBROmJzotpVY/N4TNf9gg==,type:str]
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:J2Sv/hXPsoh0zBuv5GzXk8Wp5LoqjZRcduw4NXQHkTdiUL+Vbw==,iv:m6E7oDW5rZVdl6GlKSxs+hkpzP/cboXTwEHOuLZQgqw=,tag:XO4HSFfH6kjujMbaK2FmbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TXQzVFRXYmpLeFdXVGw5
            VFpmbW1ON2hkMTNMakMvbTRFa1RXLy9TR3gwCkhOSjBwOExvVjBRZjk5OGllejhm
            bVJWM1VOR3F3d0d4QTVOOEkwTHdGdEUKLS0tIDc5KytzUU5Bek9XWFAreVF6MVJr
            cE9kelB2WGNmV1JYWHdsblEwcitGT3MKsAWV67Af3LS3G8nxlhMKi+tKyVXeLaqZ
            Tjm5rIBmx/Clj4stt9foY4XoyaNE9xaUrD7GRnldAaScKVW5G5ra4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-27T20:21:54Z"
    mac: ENC[AES256_GCM,data:6aQrr/fG7SUOsKxujTrIs09KAuBCBUbP3DOR49te8n7TqZDh9K0xWxZuEryjv9R0JndhWindKb0Eti+VQTH9k7vxBAWmPPpb6Di4NjVL8lpRNariaRcq1Sq6vvR3bHVGU+pJsXtZTXCQTLJB5HNgd35VuPQbCVHuZh6V3ixiEww=,iv:S+CvZRBy+/5/AJNXHwGoPcPdU0UO8vu3xXBXWlGS7AA=,tag:2Pd9iygUY5CqiRiQ5d07TA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
