---
kubernetes:
  children:
    master:
      hosts:
        master:
          ansible_host: 192.168.2.6
    worker:
      hosts:
        slave1:
          ansible_host: 192.168.2.170
        slave2:
          ansible_host: 192.168.2.222
        slave3:
          ansible_host: 192.168.2.208
