apiVersion: v1
kind: Secret
metadata:
    name: nordvpn-config
    namespace: default
type: Opaque
stringData:
    PRIVATE_KEY: ENC[AES256_GCM,data:lhqW0d7AgtISURUlvj7MY4MiTGV864m7nxTsDN1uqV8VPerzakFnGZYuQl8jCkhtM73uuZqWsFA1uUeEFr6Rmg==,iv:kvBVB+5hP+YThmG38nYeyXj7jcw0QgCsfW3EBlPlXXw=,tag:/7cY4gpZ0Jibih2+ZYhyYQ==,type:str]
    NET_LOCAL: ENC[AES256_GCM,data:kr9XfkkHZ5tPkpX+47I=,iv:I1I0QE4DgVW+GQ5f/FyShmqZGL7aMqqOK0WOd3rNqCk=,tag:XjCyE/CokqdZpkFejJa/2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmM044ZGxaZERDL2M0SlVP
            bi9IQkRBYXJHN0MvMWkyWVFySW9xL2dNeFdrCmFJOWJhNk5PYVd1a0p4TDlrbkV2
            czVIZ1RMOXdERThkc0ZZRWFadmdzU28KLS0tIGh5aVFjRmtkay96UFFsem5QMW1G
            alE4bVErLzhxYlM1OG11dGFxdlJWcmsKwM4uke/B1h71rCjZ+hlxi+MuFhoVdOA/
            jFXZaGfliulVka2eV0OGZkf/+SPQUXoN7mmgLrjI+RuPmrZ9Ch7FXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T20:18:23Z"
    mac: ENC[AES256_GCM,data:VFKICrF5rXAmjOIw2zCGCTSbHoz1kKD0ythaWa2eF3Zs4Sta9Mj2lGwT2wJCLl+lyaWRj4J01yUBY6SsA6KgxB6ICLSdVtGlsXn5vc8dntQUV0RSE6Y1C4qHMy1WxCK+Y/jqwu1rxG1s1aRrvU760RZzmQuukb566U1R8ML2ZPI=,iv:9KXxnGuBZN/xgq6Vc0KANLp7o9c7eJQsNnOL/5uvQ6c=,tag:2ArPrL4mAvr0qqkeCzI8AQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
