---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-cloudflare-operator
  namespace: flux-system
spec:
  path: ./config/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: cloudflare-operator
    namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-cloudflare-operator-tunnels
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cloudflare-operator
  path: ./kubernetes/apps/networking/cloudflare-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
