---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
spec:
  interval: 15m
  chart:
    spec:
      chart: loki
      version: 4.4.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    loki:
      auth_enabled: false
      schemaConfig:
        configs:
        - from: "2022-01-11"
          index:
            period: 24h
            prefix: loki_index_
          object_store: gcs
          schema: v12
          store: boltdb-shipper
      commonConfig:
        path_prefix: /var/loki
        replication_factor: 3

      storage:
        type: gcs
        bucketNames:
          chunks: home-ops-loki-bucket
          ruler: home-ops-loki-bucket
          admin: home-ops-loki-bucket

    minio:
      enabled: false

    backend:
      replicas: 1
      persistence:
        storageClass: longhorn
        size: 10Gi
      extraEnv:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/loki_secrets/gcp_service_account.json"
      extraVolumeMounts:
        - name: loki-secrets
          mountPath: "/etc/loki_secrets"
      extraVolumes:
        - name: loki-secrets
          secret:
            secretName: loki-secrets
            items:
            - key: gcp_service_account.json
              path: gcp_service_account.json

    write:
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi
        storageClass: longhorn

      extraEnv:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/loki_secrets/gcp_service_account.json"
      extraVolumeMounts:
        - name: loki-secrets
          mountPath: "/etc/loki_secrets"
      extraVolumes:
        - name: loki-secrets
          secret:
            secretName: loki-secrets
            items:
            - key: gcp_service_account.json
              path: gcp_service_account.json

    read:
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi
        storageClass: longhorn
      extraEnv:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/loki_secrets/gcp_service_account.json"
      extraVolumeMounts:
        - name: loki-secrets
          mountPath: "/etc/loki_secrets"
      extraVolumes:
        - name: loki-secrets
          secret:
            secretName: loki-secrets
            items:
            - key: gcp_service_account.json
              path: gcp_service_account.json

    gateway:
      replicas: 1

      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host loki.ninjawombat.space
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
      extraEnv:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/loki_secrets/gcp_service_account.json"
      extraVolumeMounts:
        - name: loki-secrets
          mountPath: "/etc/loki_secrets"
      extraVolumes:
        - name: loki-secrets
          secret:
            secretName: loki-secrets
            items:
            - key: gcp_service_account.json
              path: gcp_service_account.json

    monitoring:
      serviceMonitor:
        enabled: false
        metricsInstance:
          enabled: false
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
      lokiCanary:
        enabled: false
    test:
      enabled: false
