apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik
  namespace: networking
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
