kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kube-nfs-pvc
  namespace: longhorn
spec:
  storageClassName: storage-nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
