apiVersion: v1
kind: Secret
metadata:
    name: nordvpn-config
    namespace: default
type: Opaque
stringData:
    TOKEN: ENC[AES256_GCM,data:7IPHreXDYL2xtD6uZNsaFE2PnsrM3BsWc2TkwVL3NVAGXB05diPwhKFCwV7ay4m92F13yTg4Y3PWr8qrUilKbg==,iv:9BWRpGh/iAIZHWTd6+VqrMw7vK6iuOPGG6JjvfVtp4k=,tag:1gGIKtaxWoUPQM72NpM6eA==,type:str]
    CONNECT: ENC[AES256_GCM,data:gZGVpI0=,iv:5Luw92fwsXHYngfe2mZvZvOu55BA0CrlSTm6WJYKnoQ=,tag:GPoVyAWrW7/xF5UBJq9K+Q==,type:str]
    TECHNOLOGY: ENC[AES256_GCM,data:VjzA5afS0Yg=,iv:hZdbbmbFohGYkoxB3p1V18SCVEwu2BD+7lwdiCyLQiU=,tag:O8LyW3Exrv5/vbXuEvFUvg==,type:str]
    NETWORK: ENC[AES256_GCM,data:CJzVc+N5NYnzRCzHVqQ=,iv:1YGSah0fMH0EtCgbC10IKeIErT518oO3aoj3T2K6uFY=,tag:Vdr+TYVRbiVtZ5wl8kCgJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NVpGOHoyVERNWGUxQnpy
            TEJjTlh3bVoyWU9FNSswdkJGZWhsVVdleFNvCkx6WUZYNDBYa2lWbHR1TWprNUp6
            MGJFaEhVUUIyQjJYYWdmQUpEQ0tkWVkKLS0tIGVXendnU2U2NDVabGJOY0JJK0Vn
            U0t3WmxsbWdJRUNmVHZKUzJvWUNQd1UKtFAgNW167NHfZMnzwNOeG021pO2Aq613
            IuE43X4B6eMcdGjEg046B6RBTjky8ptDAJ8GlUuDigbwhIwv0ej0fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T19:43:13Z"
    mac: ENC[AES256_GCM,data:QPU8baG6E05Ftj9KCPRWxjTNSg9cH2wLtAvVUTlnNQqrlkWAyfzDY7vTSSy6wt9RsjRwoVXZlGTSX4w3vfLQf3jwHGt6kmTMd/6i9QfLlGutKPPAm+2g0IfpJEFWb/7ic/xgzAfxzkwbLdJXska7j0zc0j+ARRP0A5h1ElJ/y+k=,iv:A//riOfyup6e0LwH29RJ2Bmxocr8iFSe1Q1MFf92EqQ=,tag:TYxQAOIPoABUtj/o8TR+4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
