apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:0F/17S+T1wPQlADR1HJmKiKmLDQQpmCXJ/9bB7ryfbgKhKQKXQ==,iv:DXMXq0HMTRpN41qWnuQ+LF4AxzAl2SUv/2jOIQa5taE=,tag:bdgV0g2T1eFS+227GT7x1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubENyeFBIWE92OVdNMGJs
            WndBcEoxMjhLbFlyWUduQ2dTczFjVXVtVWdvCkVqTWViaGxiZ0JwNk80SG42d1JO
            YnVmS1k2bHZhdG1NOFUrNjFoS2FpY3cKLS0tIDlMOGVRRGt1QmN1MUdiL05ZUUNx
            aFRVRTFINzlPc0RjQ3hMRktValR4YWMKMWrY85WPhldCDtoHWiD/tJtmI16AaYR0
            WXHx6P62jkLWGMlOxKwlq4hXK25BaIwYqdw3TJjkPcWwAs9L1zKkyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-03T23:27:18Z"
    mac: ENC[AES256_GCM,data:FASZ5tEYnpvenyRFYsfQHmqMA2C+2lSGqg8x06uwyt6zIx6L74BkK6+J5iMmxJ+ck4I7rTpGNvq7Q4Ruch517EideYqOuxOtBmPKQpCRW3ClWOEtLt7UGURg53HEDmEh7ctiT5iygwHdF4nlKA5YFEoVz346ot8Y9eLibDeJwFI=,iv:kJgll+7kRdeil3mvpamAzfmEXqwbYGjjtFXIOExbqMY=,tag:YdzvPaQ5w3UYlpMPj/hfTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
