apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:uv7HwZbs6ipbTG8FoPzk3eUJ+Itiei0bfoEDWBBwz8DzurG3vg==,iv:ZztyqmkLdAKSMcrcrSLt+vTqnMWcWCCYjGQ7n4EW0AY=,tag:zF5CggHa5gee12/yNFCRbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZzdmQ0toMkRxN0tvaUJ6
            dWVVWVpHTlZ0cmg5UGRqVVhzeVZJT01SY2xjCmJwVzFWZUlsbnVGUTNuNjhsRUxr
            dDZHN2FWUXpkUGQvTVpOME40ZnFxQ2sKLS0tIGZqaFNxSlVUUlhqNHBSMkdLOGdP
            dWV0WkNUMXlhRjJFbmRYMUs5alh2RU0KkrXKYVwpVQhfp2VJdQHL2IXt71K1qJyi
            twky47P0yN87Q+j/AaP1GUII00NzJ1OUZKQqeN32TZ4u2zwmDfBlBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T17:26:47Z"
    mac: ENC[AES256_GCM,data:l+Rz6FMZBpQ/b9uiUF8jxsE7NLlla4qXZvTCuObzsyATTQH/T8VAgdj0Iqy+OwSryyuM9dp5tTaJpFXvO5c96lONVAJL2J4JUDYtgkLXFvauAdIFF0Mn5Tp5HQbx+MDwohK6D8E/uM5Ubzn8J0/grW/v+cPBlS6BtyPjp0eztcY=,iv:rF/gW1gWUi/ui1ftcB77si8/KRUQIsK0yQnepKIMKCs=,tag:1KGVhtnAXikcbaxVZul5XA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
