apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:hKyA2RjPiYJK5NFb0SNwoIZMfavKQJI8hK1JiA2+qmU6ahBIFw==,iv:zaG1vVgsPkfYRhNawjdqjjBottpleVTBJ+9ASJ3clI0=,tag:PNliieJtEzitsWhi+BpZlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArOGptREFkN1BhZGFGNU1P
            QzNqTE8vdE80bFFRam4xQWF6YTlWR1Bkb2s0ClJNQlZSMzlwVVhUc05zRmUwdng5
            VlhYcDRqUVNUdDdnalVodGo1OGRENncKLS0tIG9HSXkrTTZBUURIS1hja1FXOThR
            SldtUEdLQWxiODl0RGFnbXZzdCtQbEkKVrFRA/xBtd1g+0TtYghW7BaWwV02TWHE
            u0qZuXlbN47O/tT9jz755ECDNCUDiT6pun8bk7YpHm5LuVu35J1mcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-24T15:49:48Z"
    mac: ENC[AES256_GCM,data:z9k5Fw5+WWEo7v9ymkRsuptZIL0HdlWBkr/vGwNSIVC0AC9Fl5if0jGb62hIDa80F8lrwl5gsg3NqSUAZWw2j8fGi3jB28gZzme8gs31UTMCHJvL7rQmzOjKXLG30uwFRuHNv67BwZxaSe0C1WPt+69RKSlE9CncyvUvUqsZxeQ=,iv:NU19k8IoKD8OFt2KBbbmaGRFurTFw8RvqITBP6H3e8M=,tag:M2wdpcrFDhtyKa1cqU2M9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
