apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:ee+/lxcdvvA3riw18HTvMsUS0xpfyNnXXuicJ96alE674O6qeQ==,iv:E4EpgxQToFYiWnHxLPU/h93ozC7dsHjxafgsvDMNmqY=,tag:UuzQjElENVqqkfuuhsn0cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTM3o5aTl6b1g2ZmFRWERK
            YncvTWt5aW14RmNOVHBRY3FEQXlpajVtdDBnCmJ5YUZTTjBXR0RiaTQ3dDBuV3lk
            MVpVR1pSQlArN2dLWXR3WHc5Ty8zN1UKLS0tIGtZV05PeXFHeWR4enNhU3c3WEli
            UG4wTExTZkhBaE5lbmQ4SHNSbzhYelkKBIQZvf/tRGKCXMTTkHVEX3ufDCQOMkIg
            LNImuggOU54bklbXUknVZ9cvtJoxHTB8LXHi+KrihAvmeoVAa7fagw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-13T15:08:13Z"
    mac: ENC[AES256_GCM,data:LgMMmKInoWBCYRCIE7UEdCj+mif1/7xI2eRiXnIUgxqI8QemkAOuvm5prCk81Lh/FjQM48ekUZWGlWyG0MHv8KdpRUwiwGi0Uyy1z+fh0nlTPO/6pEUkwBV148+v9picTTIEazQitUoESApTIeQya5oxypq3bEfWhP7bWsgbIAA=,iv:HktUz3syeF0mRWT8NbfX0RcyGEBi8hD1ldAyYlzodh0=,tag:LTsVLHtCzxDss08AppHY+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
