apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:CxUHSvuYo7sw3c6oWB3xOs3Fa7rWR8liIQckk3s5HdC/Q6NtRUmcSg==,iv:MKj2JywbtTvuq3bHdk7ouTf5xuLPzWUzHKhYh91Z2LM=,tag:GjkAhBnBw8BVExzRhyH97A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLU2pBZHEwSXB6S25Jd0lm
            TFhxTXNiZnQwYjBvOVVFVnA0Rk5Jblh3dTFFCmhMeEZ0MnM1TEVLck9tOHFNWGZL
            K280TE0zK2F2ZGNBUDlFM2ZhcGIzMnMKLS0tIDVGMXpiaDZ6ZFA4VTFEcGhOekl2
            MzdtNWM1ck50REJJUGIwalJMRDhkYzAKxy9QVae2ohpfWOYOByjGcuxHGZ5LuZU7
            MGNahSaAAVdMQut81xY9+rVAx0qKyRuZCFa4XhLrcgDR89ZIqJjV9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-21T15:32:50Z"
    mac: ENC[AES256_GCM,data:4KG3hd4/1UiiIZ1vOXSMyeoWqz1M6/TZ1joXwbSpCVkIVFT+KMyrxd3Et4zzBAsLpeEPIGF7EkZY3ByWrrULBTxulISNOn1bQoETQxOb038wwosPW/s63Z4Qc4iPi9rEecJT1xikDQLzAVZrKydfuNyME7n7ijGHeE2s1cu01xk=,iv:U7gcS0P0Li4cONQjqdAqIaV3taVRypLdmNfPaMQNoq4=,tag:DdbQMIO2fPlKdDNWezyF8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
