apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:eBLmGoIMMIDc/4n/n78zbK9tdBtXPQnXCmNF62Uh/BqyPagxPQ==,iv:NSXmQ872PLqJjSvukwnsf6qDusNwaGVpO5EGKuPT+/U=,tag:sth4XFci0CALNagixwPtfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3V0g3aWpXRHJzY2F0b0pJ
            R2pxUXU0ZjNRVEZCVWpJRmhCU1hjeGk3ZlZzClhJdVB6UmMzQlkrQlpKbjRNanV6
            bEFJVmJQRTgxN2dnZEovcXdZaVY4dHMKLS0tIER3ZUZNYThES2x3cFJzQ29Oa05a
            TVJ6dlErSVdhaVlXSzdtMDBUa0VQTFkKYFci1SA/gk102Oc3P4hI0cn/6mOO1HV7
            0MdcACbMbVI2myyx0OFIXZfX+zHNojjuum9hl7QGkkT9EyHWpRlM2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-27T15:20:36Z"
    mac: ENC[AES256_GCM,data:xTcQRtZlDKN27X+zHZbhuFhOPlkIz8ZyKw/XlKX/ugf4r2rmA4g2KyJiWejKSWQ54G8QPf7MqbwQbxfi+lU0pVMkht8SH/tOInfnmNHjZUT1o+XJy3gDHNHIxTZl48BD5QNoUxJBpjtky+6lB/hKhhoIblyWHogR09b6r28AyCU=,iv:O542ANmElyLuL0g3TtU2a5C8Y+uOTX7ZciKFKttiMW4=,tag:zCp7QTs+FNfJ18DYs7Wwsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
