apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:vlbYY3wWk4LYlH5z2SHLjftLENIzEw==,iv:CTXeOdrCuryYfMI7lFBcsfQXeRbtPybybjhKNPX1XO0=,tag:l1FpJtIP4KFFFJMqaZYobg==,type:str]
    api-key: ENC[AES256_GCM,data:Mn3AN9ZNN5tRMG4YhxefZKFsvwqNzBZl/s/2gc+EayQSkL/75g==,iv:X45zvamWumdrsFshMNqkIS7pZ1HoHKFX81J6G2QOv5k=,tag:Ct1MT6hEu033MVObQlV6ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDczZIYUM1ZTJVWjRwYWhX
            UmhwZ1ZiMUJJYUJ1V2d0TDFMblZDQSt1UlUwClhPRnF2K0lUTURIUm11WldaeVlM
            SzRWd1ltc2Uxc2gvY2gvMGFlQ3o4eDAKLS0tIDFWcWZmcnlmRElONFM3YTc5VVRs
            K3pJSUdzWkV4eFFjQkl5N0JFR1Zjbk0K76kgq4vGpJr2Rbe4rZxsNr5Z7mrU2TPA
            wKcSqunmUPhZ+bZytJ4yaDI4O+InJxKCTifU6tFZM9j/t+px+5OScw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-27T19:45:47Z"
    mac: ENC[AES256_GCM,data:KkWvmJJ3DQRMgz+KIyqcq71flCmetmF9FnzfP0aSWvNRMoi8pqZrECgwX0qlQvBfKwry+i4W2oL8TK00cMzQYZH3rYSyatpTJ3YrOHwCNhTAJQLDYwzLA9upuQ8GPFfYUa0hdxRcPFCMS7WgTYPGstEmGrvCQzcB4rYW1c7euJc=,iv:wNOCIwvgd+S/cWBy9WObUAjx0+odNketV+gMM6ILI/M=,tag:xQXYS/UPnZHTAzbuEee6eQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
