apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:1yJZ9fT8HR/3BWtSxaJoiiD44i38BA==,iv:x3gCxVyIjOpH/eaamrYLDRX52TSJKvqrS7eaShhKeWE=,tag:HJO2UoscWXdSY5ksIo2nXA==,type:str]
    api-key: ENC[AES256_GCM,data:Gz/uvou8SxsAPWk9qr1Y0UvYkhmYvUlwqDpgcq4W+015FC+T+w==,iv:xR3QIXiPCRRNiz9IvWkUt5Oh6+r5UXuOOfPXYu5ypDg=,tag:cUJnZB1+A7LYnC8Q8dY6lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhKzB5TlprMGR3OHkydHdW
            Rk43QmFVTHllVVQyOHVFa0JpRDNNZkQrTWdZCjZwK0NFY2E5RVBOcEY4NmxXK044
            NmxvRnF5ZG5CNHpJeWNDTTlVUklNYW8KLS0tIFZjaThOcDNkcHUrWDZhK0ZhM0tS
            UThYUmJIdk11QUxEVUE3VnIyajBDdjAKKeyjxDqifa0Kf01i5mrxHnNaT+67E1aa
            XdNtLTrxtenuI2hAPMqPSIPXry5oWL52Mt+rejXHAR0oQg/xGjaKYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T18:40:31Z"
    mac: ENC[AES256_GCM,data:u9F0B5F2/gxG3cV31lU1y1fCIWSOgOQ/ygwYkwCiYj79o+1enP1r5KVwJkqBAbMOJ80OqRypdr83P5y0s/MvSLWzULbbRLw73bwHrk9q0Lbk5V+5d7OBS2GJiHAjbpoRqs0ojkNKX3Vw9ZDM0JTE5WW5A+T7IHLeP2YIQ3PK3tE=,iv:Os63hu6cyXTpmNVis5xHL32aSkeuxQv9DGI+rvN2eWU=,tag:feAqb5qVoodAePm64DnMww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
