---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-operator-secret
  namespace: networking
type: Opaque
stringData:
  token: "ae6a1445cf5317cf9f8df39b14ac8cc246983"
  accountID:  "luisramos191@gmail.com"
