---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - ./helmrelease.yaml
  - ./cloudflare-tunnel-operator-secret.sops.yaml
generatorOptions:
  disableNameSuffixHash: true
