apiVersion: v1
kind: Secret
metadata:
    name: test
    namespace: networking
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:oLSuuXCTQKtnAs1Nv0rMmv3j+Nozx1lMrkPfLRdDsKbJ9/8Plw==,iv:X8HKEzVNi0uY2dPu5k27Fwa/gTMOxqRBu+p8BmQ+XXc=,tag:/3e6aVOn5INyh9nTr7Sv6w==,type:str]
    accountID: ENC[AES256_GCM,data:vdC8Q8i7n3Rirk0ax3q2huXbZRm1Iw==,iv:o+xWevumFIqxspIvAmNulsgsYbQDteMf6L92n+8SXew=,tag:t1Jk82uydsB/1Xyu79mk3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSzBEYll6Z1pYSDJyUURp
            OW1uTFBHQStIUWhsMVZMQXdTZWpnMVgwSDFZCmU4bERMRy9rZ1VUbGRYM3VCY25x
            cGxBUXdwSERRYUdYcGc0YjJDa0tNL3cKLS0tIERodS9uK2xTOFJwT1U1QjN4ZmJN
            dXZ6cWlHTWI2M0lOTjI5OUVWMHg5VncKR2Bltx1Bul/RsMgOVmWpczpkYdOExndP
            ML+GY+w9uBqtNfvwvz69pRevFQKbuLFMAF8aZ1eDf0rvyRNt/4HJCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-27T18:18:00Z"
    mac: ENC[AES256_GCM,data:jfEueAy/06hjzDw/82QnxLSwr6SAgiY5Mx1tJlFMcgPZGbrkWzc/3iScaXRvOUbmWn/oEpqmd/KdHaDvmikJMfeGAeDiB/VR9VWuzVLzr+xJ3Mip91Zt0U5j4hrgzZYuDxn/OCFvvWLsg4QAwJS2lS82Pq9SBbMKoFOplVPIoYM=,iv:XltaQdNxmPhPp02wn8gOl39h0oWN+JDuwqBQ4Ve7Luo=,tag:xzRxgSZvBz+NXH2OCkFcIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
