---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 5m

  install:
    createNamespace: false
    remediation:
      retries: 5

  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5

  values:
    persistence:
      defaultClassReplicaCount: 1
    defaultSettings:
      defaultReplicaCount: 1
    pspEnable: false
    ingress:
      enabled: true
      ingressClassName: "nginx"
      tls: true
      host: "longhorn.ninjawombat.space"
