apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 5m

  install:
    createNamespace: false
    remediation:
      retries: 5

  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5

  values:
    persistence:
      defaultClassReplicaCount: 3
    defaultSettings:
      defaultReplicaCount: 3
      backupTarget: nfs://192.168.2.51:/mnt/md0/appdata/longhorn_backup
    pspEnable: false
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns.alpha.kubernetes.io/target: "192.168.2.174"
        external-dns.home.arpa/enabled: "true"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      ingressClassName: "traefik"
      tls: true
      host: "longhorn.ninjawombat.space"
    longhornUI:
      replicas: 1
    longhornConversionWebhook:
      replicas: 1
    longhornAdmissionWebhook:
      replicas: 1
    longhornRecoveryBackend:
      replicas: 1
    csi:
      attacherReplicaCount: 3
      provisionerReplicaCount: 3
      resizerReplicaCount: 3
      snapshotterReplicaCount: 3
