apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
spec:
  storageClassName: nfs-client
  capacity:
    storage: 3500Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.2.51
    path: /mnt/md0/Video
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: default
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3500Gi
