---
k3s_version: v1.26.0+k3s1
systemd_dir: /etc/systemd/system
#master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
master_ip: "192.168.2.7"
extra_server_args: "--disable servicelb --disable traefik"
extra_agent_args: ""
become: true
