---
- hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - nfs-common
        - jq
    - name: enable services iscsid on boot
      ansible.builtin.service:
        name: "iscsid"
        enabled: true
        state: started

    - name: Copy file multipath
      ansible.builtin.copy:
        src: templates/multipath.conf
        dest: /etc/multipath.conf

    - name: Restart multipathd
      ansible.builtin.service:
        name: multipathd.service
        state: restarted

    - name: Creates directory /mnt/k8s_data
      file:
        path: /mnt/k8s_data
        state: directory

    # - name: Creates directory /mnt/k8s_data/hostname
    #   file:
    #     path: /mnt/k8s_data/{{inventory_hostname}}
    #     state: directory



    - name: Mount an NFS volume
      ansible.posix.mount:
        src: 192.168.2.51:/mnt/usbshare1
        path: /mnt/k8s_data
        opts: rw,sync,hard
        state: mounted
        fstype: nfs
