apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./gcode-files-persistentvolumeclaim.yaml
# - ./klipper-claim1-persistentvolumeclaim.yaml
# - ./moonraker-data-persistentvolumeclaim.yaml
- ./mainsail-deployment.yaml
- ./mainsail-service.yaml
- ./moonraker-deployment.yaml
- ./moonraker-service.yaml
- ./mainsail-ingress.yaml
- ./moonraker-ingress.yaml
namespace: default

configMapGenerator:
- name: mainsail-config
  files:
  - config/config.json
- name: moonraker-config
  files:
  - config/moonraker.conf
  - config/printer.cfg