apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: octobot
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: drakkarsoftware/octobot
              tag: stable
            resources:
              requests:
                cpu: 100m
                memory: 100Mi

    service:
      main:
        ports:
          http:
            port: 5001
    ingress:
      main:
        enabled: true
        primary: true
        className: traefik
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: "${METALLB_INGRESS_ADDR}"
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          hajimari.io/enable: "true"
        hosts:
        - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
            service:
              name: main
              port: http
        tls:
        - hosts:
          - *host
          secretName: *host
    persistence:
      config:
        enabled: true
        existingClaim: data-pvc
        advancedMounts:
          main:
            main:
            - path: /octobot/user
              subPath: octobot/user
              readOnly: false
            - path: /octobot/tentacles
              subPath: octobot/tentacles
              readOnly: false
            - path: /octobot/logs
              subPath: octobot/logs
              readOnly: false

