apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:LC6ftO83SM+tTEHDYHZCfh7REwXnM9Xufr9TGOGH4/q9Pd0EX8SpgVi1BH28v/zwOxYC6IS4iUKP2Oxi,iv:o6SiZAFfkmYRrxzEctJhwZcLCO3CEY8C6e4plSukvYc=,tag:viukjd4IgueEZo3KnLwptQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6M3EyU2FIRkkrSUswZVdG
            MFZRRml3NXg5R2xUUGNNNHhRdTB0SGk0cldBCkhPVUtBYWV6UTMybGVUbEFWc0RW
            ZU51T2JERFVFd3k1UHBaSStwUGJEOWcKLS0tIFNUQ2h1YkhoR1ZibWNpUEFFWUhj
            K29vbTdZY1BBT2RoTG9GbldrRXNydDQKELmX+fuOBzfq22YWF9jD84EVKFnaSPe5
            I63wAJRdXMs/T0t1m3d6ZPkgIKfBqj9iafKOaZhmhX9SQJUroHq3JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-27T20:21:57Z"
    mac: ENC[AES256_GCM,data:DkdHCFp/M9f/XfdSNQijgO/iDypFK78DQf2bpyjUWEHEtWziH1qUrwjAqKyZEaxlDeWtDtErbynaeK9H3h6kWO4LLJ9AB1Qu2ecJhjGp0wrDwFk86202wv/0YAvv677MEEiK3TvWSrgJIdXeGr8sz8VLVRUBuAnKU7CveTtxYiw=,iv:Yl9ssR4Idafl7RW8CjL8BjxTMFUqbpUJsA9yWBBtXJY=,tag:zqjFuOs/Fe0Xr3o6VF20nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
