apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:+FJuWbQwura28mJUAPOgIJPCjZYiAKQjkkJVSQQj5kWRsAAeWMC5mjL5mnfveCSdqlhrwyqDjA7ktZu6,iv:NujvcHDaq+3kxya2mdm3xoxdYWunLdjHmrArz6YQjKA=,tag:XvrZEiZgpyM8xzjvtGgLfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTUpLTXc1d0puZFM5Zngy
            ZURBR3pWSmtZYlpqaHhCUXpYb1Z6UjZoRG1rCkVJakdDY3F1NE5tbHZCcWlUblVF
            ZE8reU9BTDllY2FvTHQzbVdtSFJZYmsKLS0tIFBxM3ZmamxHbS8wcXp6TzlrZFJm
            V0w5SWRyYlpFTlo3blFCN3d2cUNRWTgKk11YmfEGjZeSILgbjfTK3nVwiHmk6GVS
            w+ALB1d9FHL8rWWt7I3+Z7x4Lgxv8lo4XZNPiDPwO4bgC8kN29nkVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-21T15:32:53Z"
    mac: ENC[AES256_GCM,data:lHlxZlkKh1BSqU7xRNTWCIDCRSJlxu+dz5nUFQ3+IuhgFExXTSmc3Qd6g7GuRSWzyihcsThqdICZvhOYSS4a0z9K8nM6UkuJAWMmMdDisD7f+j3ocqBteCTYbWNMpzKU9Hf2EEzwRthpVDy0RnYzT6EBA4ezWPv1XQyzGe1BODc=,iv:hBPh6YzlW7nhvUd23nhyRFbYK8NirVQwbKZRs9y4XDE=,tag:deqzx77xrrKpc31I0e+itQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
