apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:q1XFSv3dcy0QaJzzctEWTEuNP3AjOJl1QLE1a81337lyw5IJDOJVpoY4N8dEBRlhjEv+pckmv2zZNPbd,iv:uP0qNLK13yqQeLNRdBGxrFd+IoBrmqMjljCCqh2iQkk=,tag:J5t3LIpcW6DhmG+9zPJbXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUXpTT05TdzRJU3hHK1hU
            TVk5UzQvckdxa1JpdE1ra2tpYWQybkVraFM0Ci93ZmxOMTNValdYSkFObVJVQVFP
            K0lKcFJESUFpemtvSTQvbitPM1AvM28KLS0tIDc3TndoR09JZkFDN0t1ektJaHFy
            eDVDVnpIZUR3Z3U2TStLRS9FVWZrc28K0FVVIz7+PrXty75xdhSwouXsds8XUWxc
            KVgKxYhSOA8IP0n2Hp3AYcK2LGbquLnSTvC3Zw/qMsP1HzHT9RuDTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-24T15:49:52Z"
    mac: ENC[AES256_GCM,data:OqacJXsrB29jTAH7yh6X5sKajtRyrfsWnAkWtSRTaCagGT1+lh5uytt9520NL9y97l2459gNb/YO7fVccYFimcdwQWQBWO1TvWQIb4mYw4gfl8tDgkNGlnGaXbNhXuaGoBZTIrh/MkBb5hwvPoXX9cdRZcvFhtDm/nCupIMhSNY=,iv:V24kLWL+3rBotAOd1gEZXic2jh5MQJcmcgf378ZvttU=,tag:KBGnpLhwD95XAcWWZP9PQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
