apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:R6O5LOH6PEyFSotFzb0sMYQA9JiPgN3hMrHx44OjQ1bVQqqGBSbz5kUaBtnC5fuo8gKnsaYkUfIV3b+s,iv:DlAUD9khF2re1xePmXOtTFXQ1vGx+SJZ2rkNdD1FNhk=,tag:JcGunhByPQs6rJDI8+ruHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqK2ZrcnczcnZzbWl3d09L
            ZXBsVmdtNWtQVUl2dmQvK3k0RWM4YWQvb1E0Ck96Z2kwWmpmQmF5Tkl2c05yeGUz
            UUlHc2hnSkNkZzl0REFObTQwUG5mc2sKLS0tIEVqQ3hldzc3d3E0aXo0bmVYTGRP
            ZVVoL2kwYjdpcEh1czVCMEpQNG53dVEKJ7mY0au4w4bry59QQwA5wp5fYYXESNY+
            lUaYnUp9h7ZDwQA4fg/h5Na0BvtcHTcuXHweC/eHD3aRzPpXeBb6cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-27T19:45:50Z"
    mac: ENC[AES256_GCM,data:PENVskj+rtt2RL4C2W8YZibPFisssNA1sgemUgPu/07hKXuo/SvOnMc/v1+IuqKpXKY0ppq7vdg9byGwZyJb6udJljiE4sOOFRgSd7BSOBhKp3N1/UYGMMQTZb7wX9nphqGxKuCQZ7AjBwDhpJYkZWtBw/CbUDek3Fc82K5+ahQ=,iv:+LGT+DyANwZAI3KPHIIgFwfKxZVb74bN9JZjZpwG6Fc=,tag:r5DxQp61p29V47f6Dck44w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
