apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: download-claim0
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 500Gi
status: {}
