apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flood-claim1
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 100Mi
status: {}
