---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 45.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 5m

  install:
    createNamespace: false
    remediation:
      retries: 5

  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:

    fullnameOverride: prometheus

    alertmanager:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: "${METALLB_INGRESS_ADDR}"
          external-dns.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          hajimari.io/appName: "alertmanager"
          hajimari.io/enable: "true"
          hajimari.io/icon: "alarm-light-outline"
        hosts:
          - alertmanager.ninjawombat.space
        paths:
          - /
        pathType: ImplementationSpecific
        tls:
          - hosts:
              - alertmanager.ninjawombat.space
            secretName: alertmanager.ninjawombat.space

    grafana:
      enabled: false
      forceDeployDashboards: true

    kubeControllerManager:
      enabled: false

    kubeScheduler:
      enabled: false

    kubeProxy:
      enabled: false

    kubeEtcd:
      enabled: false

    prometheus:

      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          hajimari.io/appName: "prometheus"
          hajimari.io/enable: "true"
          hajimari.io/icon: "chart-line"
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: "${METALLB_INGRESS_ADDR}"
          external-dns.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - prometheus.ninjawombat.space
        paths:
          - /
        pathType: ImplementationSpecific
        tls:
          - hosts:
              - prometheus.ninjawombat.space
            secretName: prometheus.ninjawombat.space

      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          memory: 2048Mi

      thanosService:
        enabled: false

      thanosServiceMonitor:
        enabled: false

      prometheusSpec:
        scrapeInterval: 60s
        #remoteWrite:
        #  - url: "https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push"
        #    basicAuth:
        #      username:
        #        name: grafana-cloud
        #        key: username
        #      password:
        #        name: grafana-cloud
        #        key: password


        ruleNamespaceSelector: {}
        podMonitorNamespaceSelector: {}
        podMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
        serviceMonitorSelector: {}
        serviceMonitorSelectorNilUsesHelmValues: false
        # thanos:
        #   image: quay.io/thanos/thanos:v0.30.1
        #   # renovate: datasource=docker depName=quay.io/thanos/thanos
        #   version: "v0.30.1"
        #   objectStorageConfig:
        #     name: thanos-objstore
        #     key: objstore.yml


    # Prometheus operator values
    prometheusOperator:
      resources:
        requests:
          cpu: 35m
          memory: 273M
        limits:
          memory: 326M

      prometheusConfigReloader:
        # resource config for prometheusConfigReloader
        resources:
          requests:
            cpu: 11m
            memory: 32M
          limits:
            memory: 32M

    nodeExporter:
       enabled: true
       serviceMonitor:
         relabelings:
           - action: replace
             regex: (.*)
             replacement: $1
             sourceLabels:
               - __meta_kubernetes_pod_node_name
             targetLabel: kubernetes_node

