apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flood
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: flood
      version: 6.4.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: truecharts/flood
      tag: 5.0.12
    env:
      FLOOD_OPTION_RUNDIR: /data

    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns.alpha.kubernetes.io/target: "${METALLB_INGRESS_ADDR}"
          external-dns.home.arpa/enabled: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
        - host: &host "flood.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - *host
          secretName: *host

    persistence:
      # data:
      #   enabled: true
      #   existingClaim: nfs-media-downloads-pvc

      data:
        enabled: true
        existingClaim: data-pvc
        advancedMounts:
          main:
            main:
            - path: /data
              subPath: flood
              readOnly: false

    probes:
      liveness:
        enabled: true
        initialDelaySeconds: 30
        failureThreshold: 5
        timeoutSeconds: 10
      readiness:
        enabled: true
        initialDelaySeconds: 30
        failureThreshold: 5
        timeoutSeconds: 10
      startup:
        enabled: true
        initialDelaySeconds: 5
        failureThreshold: 30
        periodSeconds: 10

    resources:
      requests:
        memory: 50Mi
        cpu: 50m
      limits:
        memory: 640Mi
