apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Madrid"
  KUBE_VIP_ADDR: "192.168.2.185"
  METALLB_LB_RANGE: "192.168.2.173-192.168.2.183"
  METALLB_K8S_GATEWAY_ADDR: "192.168.2.173"
  METALLB_INGRESS_ADDR: "192.168.2.174"
  K8S_CLUSTER_CIDR: "10.42.0.0/16"
  K8S_SERVICE_CIDR: "10.43.0.0/16"
  SERVER_CIDR: "192.168.2.0/24"
  VPN_PORT: "1194"
