apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:jW/DNaoMmlJj99ta4rQKYo4=,iv:D+uh/pxNLtYP/RuhpfX2iynIuDHV6a5S+NuYfkXYHN0=,tag:BM0Zqbw2zyyT5ywMFVvFBw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:6T7SMwOFWMJQup/FY+MOsNbJEvP/lg==,iv:Zip1UZF59bF0NVAzCQoqfaYsskuwca+Rqhv24BJFgo8=,tag:WSQV5ZuN6K34xyn8Wl5kBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVUpHSEp3WThLT1JFYksx
            QTc3ZlRPSW5lMEZDU094QzBweGU4b20rckdrCjVPb29LNEs0ZHNUeU5JaFNsRXVX
            NlQrdWdWQWlXVG1NTFpVWVBwQlY4ZUEKLS0tIGl4TVd6dDRtM2ZaZ21WWFVWem9o
            UjdJbWtINDQ0UkkxRUhBWWUvQ2lhQVEKjpJN0DmD6BCAonakqP8R5Ikov9idQuoA
            XhlDf8ebS0h5OAsBnKj9PclAtaoNTIa+PKVyn706WPfQhfqwIq89tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-28T23:44:38Z"
    mac: ENC[AES256_GCM,data:xqo05AHXsVDbHa1Tr1AjAYpgzbW1SwvZNXnbwTKfG9ZjYdUqXQ9juqXJTPSH83bbpj7gobTh+iciuFfszfephvvtXEfy37Ee1AdeRaVMXMI1kGiyhhie701EZZ4P/PW5Ed3ZM5HjuN4Tc0cqICG8rfa7Gon1dto5Ej1rVFh3CPY=,iv:K4yIACm/TcB0WjxgyFrIT6fyl2BG419KZDh5VbDLqHc=,tag:csmkLKKqYZKry2z+/urGXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
