apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:lzk1MbbWPwpz3psJUnp3uIk=,iv:gdg95qzcoYbn0/v+C/79WtYV5oEZWkz/kxOONBTYhbk=,tag:6IxpGlqMvqY3osICqI7Oiw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:O2zjb4+uXpSe3Ox3IklIIZQkvK5n3w==,iv:ApuBW3vsETYgVmObRrPkct4eEy7T8MKsR9Ss3yAQv5c=,tag:YfU7+fYJtEK/9NTYKrSD4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZ2hySzR5ZkJNU25QVU5B
            d1RmeVZROTIvbzlJNUxTWUhza1BDd3hvOWowCkgwWTFseG5LaUVPaGxmTVc4WHUr
            Z3dZTDI2NWptUVg1blFnQ3VEcGtMdDgKLS0tIGhKd3hzRTdaUGJaSU1yUFViaXls
            dFFWTS9tUG5oUTBSRlJLQ29ZTXhVY2cKyMbYjJonUZEGB4G0vFsTvbIrGD4p0CHX
            iJGS2KEPin9mP3nh3xizacBvHAEjf0z+TN1NRa1EL39ik7Pwg0dcaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T18:40:31Z"
    mac: ENC[AES256_GCM,data:hshxiup38sPYDitY72m1/KmjH2mtzvdkD7E0pwY5Cl8BfUFcc4D2b9n99zFMS1si5aEyDom5ac9RLn0mKMpJLi/AFJ3BDu/LW1VEn6rSi3XeBssgtK+RIo0DanqvxGRkMh2/hHZafOX0Rt+L2l4k31vI7xEz57jyOGErVj/Jd30=,iv:/skV6R8WTpO10MbuhKi0EUZfHdjfstRB64DZITnbtY4=,tag:mY1fUK5VMrGkCZc2ZfLahw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
