apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Qsxws5XowBmKrjZrFzjVZy4=,iv:FteeBCW5bTlUtIW3AUWwyWXuwCG3awF2JsFdntWHte0=,tag:z3n326iDr3jZcn8CWc4pFg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:7qvNZtH/geAYElchKK8i7ubGEnk4Mg==,iv:HoWODv7eGQjS/844G5rhQ42HgcirukkemErwrKxWaC0=,tag:cD6EZ4XBcR6lp0K+lyCVSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGakxlcFdZOWJnanNYVGcz
            dG56SUNQblBBVjVKaDhVOVVMNWZWWTgyT0dBCkU0TjV3aElkRjZjOGhhMGNqQmZi
            YTNGVGRmN0Z6TlRac2M0RjNoNGIxQ2cKLS0tIFFNdjhVNldVN1RTNS9teWlqK2U4
            c3FOcEJRa0l4L0JET2psRWljYWNqcWsKp6U0xFRq7LyXFZI0H0kGz3AEVz07R7mK
            GV4gemItovlb2AX40MqwZ9GcJIHcy15odP8GJYlomztHR4/8ZOoozQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-27T18:48:25Z"
    mac: ENC[AES256_GCM,data:X/BiHz8Yo/R6o4DtZaFRUxLIqHjqPPPijSsvF/ncnEu4S3Y/wufTn91vdGcEB1V7eAiU/np23MX/SDvEoGV0hW02fdlCzkp5hzF/f4ReQmGwxJ8DTNBdDW7WFlcM3csqhDgVcgXsonViim4Zg/cZKE5wkfc8Biz9avev+3/Dwmc=,iv:5YkWXWYcZSjV4rPoIxZG3FzpwdiRBuc1tBj28q+1VTQ=,tag:rGGDC/+b1Zh8EM8hkjQ+8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
