apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:11V7RNPytaRKlJ9IV2TFzPY=,iv:CV9zW3yNFU5fLIG4AKF27RkSHGQfN+bGzjvkIeVxS78=,tag:P2vERItmcxNwgGNfxw1XvQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:6kk7NE5dp+UxFqZqsS7EKgzVbbc5ww==,iv:DcQ+JzprLjbSGVzYD83nsKiZB82EzQqFfbxCaBtok1I=,tag:6Qy9ck0uAynUsp6ihHmnlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNnY4UE9qZmxEaFQ2V1BC
            eEpqM2Z4UlVUWndhM2d5R3NNOTVxUTdiSGl3CkUwQnpkMzFYMGlEN0hjQ1M4ZHZX
            bUFHd3JIdVQ5Q2lCY1ltbmRzOE8xSk0KLS0tIEVUd01HNkJDcGhtRnRYVitHQnZp
            TkxxeGF0S0hhVzlGMldVME9uRGpVWDgKjGtLE68JtMNxqNPxhhcMjtXv+gYFUGuk
            66AOeAu9o1UpE4SA1QFwLa2tpylvy3AYVzRup0+ItAMXWzinMXFNKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-24T14:56:25Z"
    mac: ENC[AES256_GCM,data:eGZ2sxUO1EWIRGSU3s4f8+yEwjk3kJRlkKcpbeUUrlQRXEug+Izp3ya1HvCK2XHsXM6M2AWqZR80TvnS9Acb5xlxNcaC9F5keo6NvC1KJK+Jw06pgEedwJT1SUX+96hvDfEHDKP/pa5B4rfu+T3fr0s9vaSJRgQWKVSmyOJ1wFU=,iv:shkJpPXGsAKwqhGW2M6p68jMxqhLfcdnepyDetEvVWg=,tag:n4rfKb+vRUsjrGJSv2GCtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
