apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:4YlF8Q+JUuDsEWyTXtou/FY=,iv:OoZ8aEZAYP+YD1r/YUQclAwxPUgqJf1Kj2GLGLMVjTo=,tag:aI+0UlZyAqWfhagQFu4SWg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:RGthSt063XZ0XD24Zrk2LdI90KEmGg==,iv:X8XyCGPbI6B3hb7IyvfHfLSxsbtuAeq6gli6fJROcnc=,tag:sFPoPObDT1gK0joJ45DJsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHczJ0RjRpU2MxbHFOeFNW
            UHFJbG5adW4rTWZBaVNzbUVGMFVQRW91YWxBClZHNDNTcUZjSmF0U2JnaDI1NFht
            cFZHbzE3U3RjSmdOR2JhU1VIejhHNzQKLS0tIDdWMS9BUS9ETkU2U2xGZmJHbk5t
            NnUzMC9udzFYVnpXMFBGWUVsTFVQd0UKTSFEo9r1GSVgxH2ZEFQMGVucSH/XCzop
            NKWIfM6ZX2tynyKb5V3O7VJvIS5YXJnaHUDFsiROVLiNNfmkeWozcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T17:26:47Z"
    mac: ENC[AES256_GCM,data:li+CD5+1cqljy3lHLpc5LsV32erMIRbrpcVZF4lFYjnRWVZ3Dcqr5XJ+cKNJW/10qlUgCfnXQO/H8gA4v/bvekORWFgdkRavVDe5zxOoJYLGaHVi06KtmQnb+oNq+1MqHIClHAcqwGIkQBkkIcof3B8Al3NLrI5nATgWqLJcWQw=,iv:doxhXB6jxV/HIem20mHMXO+PD+C9E4DcATIgj83YIak=,tag:N3BLGY+fjMIjxyVk7IlEVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
