apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:GrQhfp9vDc9ugyXbjQcvHrk=,iv:qEonRreagaiwmI2Igvqhj7oseCse0NdwslQEZLdv2Y0=,tag:dB1DAjug/kho/a/oAYlwEg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:7H1lopl91itdrWuHFZEMPYIKhJXS+g==,iv:dAlscSuFAuDym1o7J2hovHJHuvRf+ZJv++cMOt91Pms=,tag:aPlCmVGaD1HsMxmq5POvEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hvkcj9lj2ghgqw0ft9xgd064pmrecm7va0shv3e20lrec39u2dcs29uwlc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERXQyTWpxMWx4L1lpZkkr
            MEY0YmUzYXlrYmVYWHJVU2l0OHBkeStQc2hvCnRReXRTTzF6SktUQU92VzR3bExC
            UGpQQWF4WE5KOWNFUk5yWWZGOW5UbzgKLS0tIFBRVE9DYjJMZmVhUFlnSzdLRzY5
            Rm1zSlpwRXlmUm1TbVFtUis1S3hidGsKN2kd8WQAh6PYWFymaoFUZfmdVR1yBbfy
            nWhYR9XgKjHKxkxA9hkT6O2/uw4Kcw2Z3Auoe25VvejYVzgOoIbhcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-21T15:32:50Z"
    mac: ENC[AES256_GCM,data:LSe8CUengd/mjSDBTXm+6SULtEGP8RZqkhFbR3td7TqbtXCsJRg85bi99OHtOt5wic9UA2TbVgg/+YqEuaAtPIj+tSP8V+VOhy93q53crKT1DCJK31iVUs05H7Po+JDlVSutEqmBJjjBgwnpHKa8PZ9f5mE2wv0Fy6zApQyhB6s=,iv:ac2XJtK5RXvWHR6opD5P4/5YvKnFcKVjRbVBYbwTaJo=,tag:VHn3a3GrlOENR7v9zEi0Hg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
