---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      version: 6.50.5
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:

    datasources:
      datasources.yaml:
        apiVersion: 1
        deleteDatasources:
          # - name: Loki
          #   orgId: 1
          - name: Alertmanager
            orgId: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://prometheus-prometheus.monitoring.svc.cluster.local:9090
            isDefault: true
          # - name: Loki
          #   type: loki
          #   access: proxy
          #   url: http://loki.logging.svc.cluster.local:3100
          - name: Alertmanager
            type: alertmanager
            access: proxy
            url: http://prometheus-alertmanager.monitoring.svc.cluster.local:9093
            jsonData:
              implementation: prometheus
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
        # folderAnnotation: grafana_folder
        # provider:
        #   foldersFromFilesStructure: true
      datasources:
        enabled: true
        searchNamespace: ALL

    plugins:
      - digrich-bubblechart-panel
      - grafana-clock-panel
      - redis-datasource
      - marcusolsson-hexmap-panel
      - grafana-polystat-panel
      - pyroscope-panel
      - flant-statusmap-panel

    serviceMonitor:
      enabled: true

    rbac:
      pspEnabled: false

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        hajimari.io/appName: "grafana"
        hajimari.io/enable: "true"
        hajimari.io/icon: "alarm-light-outline"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns.home.arpa/enabled: "true"
      hosts:
        - grafana.ninjawombat.space
      paths:
        - /
      pathType: ImplementationSpecific
      tls:
        - hosts:
            - grafana.ninjawombat.space

    persistence:
      enabled: false
      storageClassName: longhorn
      accessModes:
        - ReadWriteOnce
      size: 5Gi
      existingClaim: grafana

      extraPvcLabels:
        snapshot.home.arpa/enabled: "true"
