---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
- ./helmrelease.yaml
# - ./tunnelbinding.yaml
#  - dashboards
#  - datasources
#  - deploy.yml
#  - rbac.yml
#  - grafana-config.yml
#  - ingress.yaml
#  - crt_grafana.yaml


#configMapGenerator:
#  - name: grafana-dashboards
#    files:
#      - dashboards.yaml
