---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: grafana-tunnel
  namespace: monitoring
subjects:
  - name: grafana
    spec:
      fqdn: grafana.ninjawombat.space
tunnelRef:
  kind: ClusterTunnel
  name: cluster-tunnel
