apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: thanos
      version: 12.0.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m

  install:
    createNamespace: true
    remediation:
      retries: 5

  upgrade:
    remediation:
      retries: 5

  dependsOn:
  - name: kube-prometheus-stack
    namespace: monitoring
  - name: traefik
    namespace: networking
    #    - name: rook-ceph
    #      namespace: rook-ceph

  values:
    query:
      enabled: true
      replicaLabels:
      - replica
      dnsDiscovery:
        sidecarsService: prometheus-thanos-discovery
        sidecarsNamespace: monitoring
      ingress:
        enabled: true
        hostname: "thanos.${SECRET_DOMAIN}"
        ingressClassName: "nginx"
        tls: true

    existingObjstoreSecret: &secret thanos-objstore

    queryFrontend:
      enabled: false

    bucketweb:
      enabled: true
      podAnnotations:
        secret.reloader.stakater.com/reload: *secret

    compactor:
      enabled: true
      retentionResolutionRaw: 90d
      retentionResolution5m: 180d
      retentionResolution1h: 1y
      consistencyDelay: 30m
      compact.concurrency: 6
      downsample.concurrency: 6
      block-sync-concurrency: 60
      persistence:
        enabled: true
        size: 10Gi
        storageClass: longhorn
      podAnnotations:
        secret.reloader.stakater.com/reload: *secret

    storegateway:
      enabled: true
      replicaCount: 1
      podAntiAffinityPreset: hard
      persistence:
        enabled: true
        size: 5Gi
      podAnnotations:
        secret.reloader.stakater.com/reload: *secret

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
