---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-operator
  namespace: networking
type: Opaque
stringData:
        token: "${BOOTSTRAP_CLOUDFLARE_APIKEY}"
        accountID:  "${BOOTSTRAP_CLOUDFLARE_EMAIL}"
