---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-operator-secret
  namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: "${BOOTSTRAP_CLOUDFLARE_API_TOKEN}"
    CLOUDFLARE_API_KEY: "${BOOTSTRAP_CLOUDFLARE_APIKEY}"