apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  storageClassName: nfs-client
  capacity:
    storage: 40Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.2.51
    path: /mnt/md0/appdata/k8s_data
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
