apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-vol-pvc
  namespace: networking
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi
