# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: whisparr
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
  - name: qbittorrent
    namespace: default
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/hotio/whisparr
              tag: latest
            resources:
              requests:
                cpu: 15m
                memory: 352Mi
              limits:
                memory: 2Gi
    service:
      main:
        ports:
          http:
            port: 6969
    ingress:
      main:
        enabled: true
        primary: true
        className: traefik
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: "${METALLB_INGRESS_ADDR}"
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          hajimari.io/enable: "true"
        hosts:
        - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
            service:
              name: main
              port: http
        tls:
        - hosts:
          - *host
          secretName: *host
    persistence:
      config:
        enabled: true
        existingClaim: data-pvc
        advancedMounts:
          main:
            main:
            - path: /config
              subPath: whisparr
              readOnly: false
      media:
        enabled: true
        existingClaim: media-pvc
        readOnly: false
        globalMounts:
        # - path: /movies
        #   subPath: pelis2
        - path: /media
          subPath: downloads/movies2
